// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Autoencoder_Autoencoder_Pipeline_VITIS_LOOP_69_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        DecWeights,
        DecoderWeights_V_out,
        DecoderWeights_V_out_ap_vld,
        DecoderWeights_V_1_out,
        DecoderWeights_V_1_out_ap_vld,
        DecoderWeights_V_2_out,
        DecoderWeights_V_2_out_ap_vld,
        DecoderWeights_V_3_out,
        DecoderWeights_V_3_out_ap_vld,
        DecoderWeights_V_4_out,
        DecoderWeights_V_4_out_ap_vld,
        DecoderWeights_V_5_out,
        DecoderWeights_V_5_out_ap_vld,
        DecoderWeights_V_6_out,
        DecoderWeights_V_6_out_ap_vld,
        DecoderWeights_V_7_out,
        DecoderWeights_V_7_out_ap_vld,
        DecoderWeights_V_8_out,
        DecoderWeights_V_8_out_ap_vld,
        DecoderWeights_V_9_out,
        DecoderWeights_V_9_out_ap_vld,
        DecoderWeights_V_10_out,
        DecoderWeights_V_10_out_ap_vld,
        DecoderWeights_V_11_out,
        DecoderWeights_V_11_out_ap_vld,
        DecoderWeights_V_12_out,
        DecoderWeights_V_12_out_ap_vld,
        DecoderWeights_V_13_out,
        DecoderWeights_V_13_out_ap_vld,
        DecoderWeights_V_14_out,
        DecoderWeights_V_14_out_ap_vld,
        DecoderWeights_V_15_out,
        DecoderWeights_V_15_out_ap_vld,
        DecoderWeights_V_16_out,
        DecoderWeights_V_16_out_ap_vld,
        DecoderWeights_V_17_out,
        DecoderWeights_V_17_out_ap_vld,
        DecoderWeights_V_18_out,
        DecoderWeights_V_18_out_ap_vld,
        DecoderWeights_V_19_out,
        DecoderWeights_V_19_out_ap_vld,
        DecoderWeights_V_20_out,
        DecoderWeights_V_20_out_ap_vld,
        DecoderWeights_V_21_out,
        DecoderWeights_V_21_out_ap_vld,
        DecoderWeights_V_22_out,
        DecoderWeights_V_22_out_ap_vld,
        DecoderWeights_V_23_out,
        DecoderWeights_V_23_out_ap_vld,
        DecoderWeights_V_24_out,
        DecoderWeights_V_24_out_ap_vld,
        DecoderWeights_V_25_out,
        DecoderWeights_V_25_out_ap_vld,
        DecoderWeights_V_26_out,
        DecoderWeights_V_26_out_ap_vld,
        DecoderWeights_V_27_out,
        DecoderWeights_V_27_out_ap_vld,
        DecoderWeights_V_28_out,
        DecoderWeights_V_28_out_ap_vld,
        DecoderWeights_V_29_out,
        DecoderWeights_V_29_out_ap_vld,
        DecoderWeights_V_30_out,
        DecoderWeights_V_30_out_ap_vld,
        DecoderWeights_V_31_out,
        DecoderWeights_V_31_out_ap_vld,
        DecoderWeights_V_32_out,
        DecoderWeights_V_32_out_ap_vld,
        DecoderWeights_V_33_out,
        DecoderWeights_V_33_out_ap_vld,
        DecoderWeights_V_34_out,
        DecoderWeights_V_34_out_ap_vld,
        DecoderWeights_V_35_out,
        DecoderWeights_V_35_out_ap_vld,
        DecoderWeights_V_36_out,
        DecoderWeights_V_36_out_ap_vld,
        DecoderWeights_V_37_out,
        DecoderWeights_V_37_out_ap_vld,
        DecoderWeights_V_38_out,
        DecoderWeights_V_38_out_ap_vld,
        DecoderWeights_V_39_out,
        DecoderWeights_V_39_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [7:0] m_axi_gmem0_WDATA;
output  [0:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [7:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [10:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] DecWeights;
output  [0:0] DecoderWeights_V_out;
output   DecoderWeights_V_out_ap_vld;
output  [0:0] DecoderWeights_V_1_out;
output   DecoderWeights_V_1_out_ap_vld;
output  [0:0] DecoderWeights_V_2_out;
output   DecoderWeights_V_2_out_ap_vld;
output  [0:0] DecoderWeights_V_3_out;
output   DecoderWeights_V_3_out_ap_vld;
output  [0:0] DecoderWeights_V_4_out;
output   DecoderWeights_V_4_out_ap_vld;
output  [0:0] DecoderWeights_V_5_out;
output   DecoderWeights_V_5_out_ap_vld;
output  [0:0] DecoderWeights_V_6_out;
output   DecoderWeights_V_6_out_ap_vld;
output  [0:0] DecoderWeights_V_7_out;
output   DecoderWeights_V_7_out_ap_vld;
output  [0:0] DecoderWeights_V_8_out;
output   DecoderWeights_V_8_out_ap_vld;
output  [0:0] DecoderWeights_V_9_out;
output   DecoderWeights_V_9_out_ap_vld;
output  [0:0] DecoderWeights_V_10_out;
output   DecoderWeights_V_10_out_ap_vld;
output  [0:0] DecoderWeights_V_11_out;
output   DecoderWeights_V_11_out_ap_vld;
output  [0:0] DecoderWeights_V_12_out;
output   DecoderWeights_V_12_out_ap_vld;
output  [0:0] DecoderWeights_V_13_out;
output   DecoderWeights_V_13_out_ap_vld;
output  [0:0] DecoderWeights_V_14_out;
output   DecoderWeights_V_14_out_ap_vld;
output  [0:0] DecoderWeights_V_15_out;
output   DecoderWeights_V_15_out_ap_vld;
output  [0:0] DecoderWeights_V_16_out;
output   DecoderWeights_V_16_out_ap_vld;
output  [0:0] DecoderWeights_V_17_out;
output   DecoderWeights_V_17_out_ap_vld;
output  [0:0] DecoderWeights_V_18_out;
output   DecoderWeights_V_18_out_ap_vld;
output  [0:0] DecoderWeights_V_19_out;
output   DecoderWeights_V_19_out_ap_vld;
output  [0:0] DecoderWeights_V_20_out;
output   DecoderWeights_V_20_out_ap_vld;
output  [0:0] DecoderWeights_V_21_out;
output   DecoderWeights_V_21_out_ap_vld;
output  [0:0] DecoderWeights_V_22_out;
output   DecoderWeights_V_22_out_ap_vld;
output  [0:0] DecoderWeights_V_23_out;
output   DecoderWeights_V_23_out_ap_vld;
output  [0:0] DecoderWeights_V_24_out;
output   DecoderWeights_V_24_out_ap_vld;
output  [0:0] DecoderWeights_V_25_out;
output   DecoderWeights_V_25_out_ap_vld;
output  [0:0] DecoderWeights_V_26_out;
output   DecoderWeights_V_26_out_ap_vld;
output  [0:0] DecoderWeights_V_27_out;
output   DecoderWeights_V_27_out_ap_vld;
output  [0:0] DecoderWeights_V_28_out;
output   DecoderWeights_V_28_out_ap_vld;
output  [0:0] DecoderWeights_V_29_out;
output   DecoderWeights_V_29_out_ap_vld;
output  [0:0] DecoderWeights_V_30_out;
output   DecoderWeights_V_30_out_ap_vld;
output  [0:0] DecoderWeights_V_31_out;
output   DecoderWeights_V_31_out_ap_vld;
output  [0:0] DecoderWeights_V_32_out;
output   DecoderWeights_V_32_out_ap_vld;
output  [0:0] DecoderWeights_V_33_out;
output   DecoderWeights_V_33_out_ap_vld;
output  [0:0] DecoderWeights_V_34_out;
output   DecoderWeights_V_34_out_ap_vld;
output  [0:0] DecoderWeights_V_35_out;
output   DecoderWeights_V_35_out_ap_vld;
output  [0:0] DecoderWeights_V_36_out;
output   DecoderWeights_V_36_out_ap_vld;
output  [0:0] DecoderWeights_V_37_out;
output   DecoderWeights_V_37_out_ap_vld;
output  [0:0] DecoderWeights_V_38_out;
output   DecoderWeights_V_38_out_ap_vld;
output  [0:0] DecoderWeights_V_39_out;
output   DecoderWeights_V_39_out_ap_vld;

reg ap_idle;
reg m_axi_gmem0_RREADY;
reg[0:0] DecoderWeights_V_out;
reg DecoderWeights_V_out_ap_vld;
reg[0:0] DecoderWeights_V_1_out;
reg DecoderWeights_V_1_out_ap_vld;
reg[0:0] DecoderWeights_V_2_out;
reg DecoderWeights_V_2_out_ap_vld;
reg[0:0] DecoderWeights_V_3_out;
reg DecoderWeights_V_3_out_ap_vld;
reg[0:0] DecoderWeights_V_4_out;
reg DecoderWeights_V_4_out_ap_vld;
reg[0:0] DecoderWeights_V_5_out;
reg DecoderWeights_V_5_out_ap_vld;
reg[0:0] DecoderWeights_V_6_out;
reg DecoderWeights_V_6_out_ap_vld;
reg[0:0] DecoderWeights_V_7_out;
reg DecoderWeights_V_7_out_ap_vld;
reg[0:0] DecoderWeights_V_8_out;
reg DecoderWeights_V_8_out_ap_vld;
reg[0:0] DecoderWeights_V_9_out;
reg DecoderWeights_V_9_out_ap_vld;
reg[0:0] DecoderWeights_V_10_out;
reg DecoderWeights_V_10_out_ap_vld;
reg[0:0] DecoderWeights_V_11_out;
reg DecoderWeights_V_11_out_ap_vld;
reg[0:0] DecoderWeights_V_12_out;
reg DecoderWeights_V_12_out_ap_vld;
reg[0:0] DecoderWeights_V_13_out;
reg DecoderWeights_V_13_out_ap_vld;
reg[0:0] DecoderWeights_V_14_out;
reg DecoderWeights_V_14_out_ap_vld;
reg[0:0] DecoderWeights_V_15_out;
reg DecoderWeights_V_15_out_ap_vld;
reg[0:0] DecoderWeights_V_16_out;
reg DecoderWeights_V_16_out_ap_vld;
reg[0:0] DecoderWeights_V_17_out;
reg DecoderWeights_V_17_out_ap_vld;
reg[0:0] DecoderWeights_V_18_out;
reg DecoderWeights_V_18_out_ap_vld;
reg[0:0] DecoderWeights_V_19_out;
reg DecoderWeights_V_19_out_ap_vld;
reg[0:0] DecoderWeights_V_20_out;
reg DecoderWeights_V_20_out_ap_vld;
reg[0:0] DecoderWeights_V_21_out;
reg DecoderWeights_V_21_out_ap_vld;
reg[0:0] DecoderWeights_V_22_out;
reg DecoderWeights_V_22_out_ap_vld;
reg[0:0] DecoderWeights_V_23_out;
reg DecoderWeights_V_23_out_ap_vld;
reg[0:0] DecoderWeights_V_24_out;
reg DecoderWeights_V_24_out_ap_vld;
reg[0:0] DecoderWeights_V_25_out;
reg DecoderWeights_V_25_out_ap_vld;
reg[0:0] DecoderWeights_V_26_out;
reg DecoderWeights_V_26_out_ap_vld;
reg[0:0] DecoderWeights_V_27_out;
reg DecoderWeights_V_27_out_ap_vld;
reg[0:0] DecoderWeights_V_28_out;
reg DecoderWeights_V_28_out_ap_vld;
reg[0:0] DecoderWeights_V_29_out;
reg DecoderWeights_V_29_out_ap_vld;
reg[0:0] DecoderWeights_V_30_out;
reg DecoderWeights_V_30_out_ap_vld;
reg[0:0] DecoderWeights_V_31_out;
reg DecoderWeights_V_31_out_ap_vld;
reg[0:0] DecoderWeights_V_32_out;
reg DecoderWeights_V_32_out_ap_vld;
reg[0:0] DecoderWeights_V_33_out;
reg DecoderWeights_V_33_out_ap_vld;
reg[0:0] DecoderWeights_V_34_out;
reg DecoderWeights_V_34_out_ap_vld;
reg[0:0] DecoderWeights_V_35_out;
reg DecoderWeights_V_35_out_ap_vld;
reg[0:0] DecoderWeights_V_36_out;
reg DecoderWeights_V_36_out_ap_vld;
reg[0:0] DecoderWeights_V_37_out;
reg DecoderWeights_V_37_out_ap_vld;
reg[0:0] DecoderWeights_V_38_out;
reg DecoderWeights_V_38_out_ap_vld;
reg[0:0] DecoderWeights_V_39_out;
reg DecoderWeights_V_39_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln69_fu_471_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg   [5:0] i_1_reg_699;
reg    ap_block_pp0_stage0_11001;
reg   [5:0] i_1_reg_699_pp0_iter1_reg;
wire   [0:0] trunc_ln71_fu_488_p1;
reg   [0:0] trunc_ln71_reg_712;
wire    ap_loop_init;
reg   [5:0] i_fu_202;
wire   [5:0] add_ln69_fu_477_p2;
reg   [5:0] ap_sig_allocacmp_i_1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_588;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

Autoencoder_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln69_fu_471_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_202 <= add_ln69_fu_477_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_202 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_1_reg_699 <= ap_sig_allocacmp_i_1;
        i_1_reg_699_pp0_iter1_reg <= i_1_reg_699;
        trunc_ln71_reg_712 <= trunc_ln71_fu_488_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_10_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd9))) begin
            DecoderWeights_V_10_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_10_out = 'bx;
        end
    end else begin
        DecoderWeights_V_10_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd9)))) begin
        DecoderWeights_V_10_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_11_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd10))) begin
            DecoderWeights_V_11_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_11_out = 'bx;
        end
    end else begin
        DecoderWeights_V_11_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd10)))) begin
        DecoderWeights_V_11_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_12_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd11))) begin
            DecoderWeights_V_12_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_12_out = 'bx;
        end
    end else begin
        DecoderWeights_V_12_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd11)))) begin
        DecoderWeights_V_12_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_13_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd12))) begin
            DecoderWeights_V_13_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_13_out = 'bx;
        end
    end else begin
        DecoderWeights_V_13_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd12)))) begin
        DecoderWeights_V_13_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_14_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd13))) begin
            DecoderWeights_V_14_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_14_out = 'bx;
        end
    end else begin
        DecoderWeights_V_14_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd13)))) begin
        DecoderWeights_V_14_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_15_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd14))) begin
            DecoderWeights_V_15_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_15_out = 'bx;
        end
    end else begin
        DecoderWeights_V_15_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd14)))) begin
        DecoderWeights_V_15_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_16_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd15))) begin
            DecoderWeights_V_16_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_16_out = 'bx;
        end
    end else begin
        DecoderWeights_V_16_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd15)))) begin
        DecoderWeights_V_16_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_17_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd16))) begin
            DecoderWeights_V_17_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_17_out = 'bx;
        end
    end else begin
        DecoderWeights_V_17_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd16)))) begin
        DecoderWeights_V_17_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_18_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd17))) begin
            DecoderWeights_V_18_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_18_out = 'bx;
        end
    end else begin
        DecoderWeights_V_18_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd17)))) begin
        DecoderWeights_V_18_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_19_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd18))) begin
            DecoderWeights_V_19_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_19_out = 'bx;
        end
    end else begin
        DecoderWeights_V_19_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd18)))) begin
        DecoderWeights_V_19_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_1_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd0))) begin
            DecoderWeights_V_1_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_1_out = 'bx;
        end
    end else begin
        DecoderWeights_V_1_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd0)))) begin
        DecoderWeights_V_1_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_20_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd19))) begin
            DecoderWeights_V_20_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_20_out = 'bx;
        end
    end else begin
        DecoderWeights_V_20_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd19)))) begin
        DecoderWeights_V_20_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_21_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd20))) begin
            DecoderWeights_V_21_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_21_out = 'bx;
        end
    end else begin
        DecoderWeights_V_21_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd20)))) begin
        DecoderWeights_V_21_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_22_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd21))) begin
            DecoderWeights_V_22_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_22_out = 'bx;
        end
    end else begin
        DecoderWeights_V_22_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd21)))) begin
        DecoderWeights_V_22_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_23_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd22))) begin
            DecoderWeights_V_23_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_23_out = 'bx;
        end
    end else begin
        DecoderWeights_V_23_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd22)))) begin
        DecoderWeights_V_23_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_24_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd23))) begin
            DecoderWeights_V_24_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_24_out = 'bx;
        end
    end else begin
        DecoderWeights_V_24_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd23)))) begin
        DecoderWeights_V_24_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_25_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd24))) begin
            DecoderWeights_V_25_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_25_out = 'bx;
        end
    end else begin
        DecoderWeights_V_25_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd24)))) begin
        DecoderWeights_V_25_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_26_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd25))) begin
            DecoderWeights_V_26_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_26_out = 'bx;
        end
    end else begin
        DecoderWeights_V_26_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd25)))) begin
        DecoderWeights_V_26_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_27_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd26))) begin
            DecoderWeights_V_27_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_27_out = 'bx;
        end
    end else begin
        DecoderWeights_V_27_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd26)))) begin
        DecoderWeights_V_27_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_28_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd27))) begin
            DecoderWeights_V_28_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_28_out = 'bx;
        end
    end else begin
        DecoderWeights_V_28_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd27)))) begin
        DecoderWeights_V_28_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_29_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd28))) begin
            DecoderWeights_V_29_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_29_out = 'bx;
        end
    end else begin
        DecoderWeights_V_29_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd28)))) begin
        DecoderWeights_V_29_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_2_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd1))) begin
            DecoderWeights_V_2_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_2_out = 'bx;
        end
    end else begin
        DecoderWeights_V_2_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd1)))) begin
        DecoderWeights_V_2_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_30_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd29))) begin
            DecoderWeights_V_30_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_30_out = 'bx;
        end
    end else begin
        DecoderWeights_V_30_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd29)))) begin
        DecoderWeights_V_30_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_31_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd30))) begin
            DecoderWeights_V_31_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_31_out = 'bx;
        end
    end else begin
        DecoderWeights_V_31_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd30)))) begin
        DecoderWeights_V_31_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_32_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd31))) begin
            DecoderWeights_V_32_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_32_out = 'bx;
        end
    end else begin
        DecoderWeights_V_32_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd31)))) begin
        DecoderWeights_V_32_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_33_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd32))) begin
            DecoderWeights_V_33_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_33_out = 'bx;
        end
    end else begin
        DecoderWeights_V_33_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd32)))) begin
        DecoderWeights_V_33_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_34_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd33))) begin
            DecoderWeights_V_34_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_34_out = 'bx;
        end
    end else begin
        DecoderWeights_V_34_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd33)))) begin
        DecoderWeights_V_34_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_35_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd34))) begin
            DecoderWeights_V_35_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_35_out = 'bx;
        end
    end else begin
        DecoderWeights_V_35_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd34)))) begin
        DecoderWeights_V_35_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_36_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd35))) begin
            DecoderWeights_V_36_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_36_out = 'bx;
        end
    end else begin
        DecoderWeights_V_36_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd35)))) begin
        DecoderWeights_V_36_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_37_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd36))) begin
            DecoderWeights_V_37_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_37_out = 'bx;
        end
    end else begin
        DecoderWeights_V_37_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd36)))) begin
        DecoderWeights_V_37_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_38_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd37))) begin
            DecoderWeights_V_38_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_38_out = 'bx;
        end
    end else begin
        DecoderWeights_V_38_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd37)))) begin
        DecoderWeights_V_38_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_39_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd38))) begin
            DecoderWeights_V_39_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_39_out = 'bx;
        end
    end else begin
        DecoderWeights_V_39_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd38)))) begin
        DecoderWeights_V_39_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_3_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd2))) begin
            DecoderWeights_V_3_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_3_out = 'bx;
        end
    end else begin
        DecoderWeights_V_3_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd2)))) begin
        DecoderWeights_V_3_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_4_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd3))) begin
            DecoderWeights_V_4_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_4_out = 'bx;
        end
    end else begin
        DecoderWeights_V_4_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd3)))) begin
        DecoderWeights_V_4_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_5_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd4))) begin
            DecoderWeights_V_5_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_5_out = 'bx;
        end
    end else begin
        DecoderWeights_V_5_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd4)))) begin
        DecoderWeights_V_5_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_6_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd5))) begin
            DecoderWeights_V_6_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_6_out = 'bx;
        end
    end else begin
        DecoderWeights_V_6_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd5)))) begin
        DecoderWeights_V_6_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_7_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd6))) begin
            DecoderWeights_V_7_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_7_out = 'bx;
        end
    end else begin
        DecoderWeights_V_7_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd6)))) begin
        DecoderWeights_V_7_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_8_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd7))) begin
            DecoderWeights_V_8_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_8_out = 'bx;
        end
    end else begin
        DecoderWeights_V_8_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd7)))) begin
        DecoderWeights_V_8_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_9_out = 1'd0;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd8))) begin
            DecoderWeights_V_9_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_9_out = 'bx;
        end
    end else begin
        DecoderWeights_V_9_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (i_1_reg_699_pp0_iter1_reg == 6'd8)))) begin
        DecoderWeights_V_9_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            DecoderWeights_V_out = 1'd0;
        end else if ((1'b1 == ap_condition_588)) begin
            DecoderWeights_V_out = trunc_ln71_reg_712;
        end else begin
            DecoderWeights_V_out = 'bx;
        end
    end else begin
        DecoderWeights_V_out = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & ((i_1_reg_699_pp0_iter1_reg == 6'd39) | ((i_1_reg_699_pp0_iter1_reg == 6'd40) | ((i_1_reg_699_pp0_iter1_reg == 6'd41) | ((i_1_reg_699_pp0_iter1_reg == 6'd42) | ((i_1_reg_699_pp0_iter1_reg == 6'd43) | ((i_1_reg_699_pp0_iter1_reg == 6'd44) | ((i_1_reg_699_pp0_iter1_reg == 6'd45) | ((i_1_reg_699_pp0_iter1_reg == 6'd46) | ((i_1_reg_699_pp0_iter1_reg == 6'd47) | ((i_1_reg_699_pp0_iter1_reg == 6'd48) | ((i_1_reg_699_pp0_iter1_reg == 6'd49) | ((i_1_reg_699_pp0_iter1_reg == 6'd50) | ((i_1_reg_699_pp0_iter1_reg == 6'd51) | ((i_1_reg_699_pp0_iter1_reg == 6'd52) | ((i_1_reg_699_pp0_iter1_reg == 6'd53) | ((i_1_reg_699_pp0_iter1_reg == 6'd54) | ((i_1_reg_699_pp0_iter1_reg == 6'd55) | ((i_1_reg_699_pp0_iter1_reg == 6'd56) | ((i_1_reg_699_pp0_iter1_reg == 6'd57) | ((i_1_reg_699_pp0_iter1_reg == 6'd58) | ((i_1_reg_699_pp0_iter1_reg == 6'd59) | ((i_1_reg_699_pp0_iter1_reg == 6'd60) | ((i_1_reg_699_pp0_iter1_reg == 6'd61) | ((i_1_reg_699_pp0_iter1_reg == 6'd62) | (i_1_reg_699_pp0_iter1_reg == 6'd63)))))))))))))))))))))))))))) begin
        DecoderWeights_V_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_V_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln69_fu_471_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_202;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln69_fu_477_p2 = (ap_sig_allocacmp_i_1 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (m_axi_gmem0_RVALID == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_588 = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((i_1_reg_699_pp0_iter1_reg == 6'd39) | ((i_1_reg_699_pp0_iter1_reg == 6'd40) | ((i_1_reg_699_pp0_iter1_reg == 6'd41) | ((i_1_reg_699_pp0_iter1_reg == 6'd42) | ((i_1_reg_699_pp0_iter1_reg == 6'd43) | ((i_1_reg_699_pp0_iter1_reg == 6'd44) | ((i_1_reg_699_pp0_iter1_reg == 6'd45) | ((i_1_reg_699_pp0_iter1_reg == 6'd46) | ((i_1_reg_699_pp0_iter1_reg == 6'd47) | ((i_1_reg_699_pp0_iter1_reg == 6'd48) | ((i_1_reg_699_pp0_iter1_reg == 6'd49) | ((i_1_reg_699_pp0_iter1_reg == 6'd50) | ((i_1_reg_699_pp0_iter1_reg == 6'd51) | ((i_1_reg_699_pp0_iter1_reg == 6'd52) | ((i_1_reg_699_pp0_iter1_reg == 6'd53) | ((i_1_reg_699_pp0_iter1_reg == 6'd54) | ((i_1_reg_699_pp0_iter1_reg == 6'd55) | ((i_1_reg_699_pp0_iter1_reg == 6'd56) | ((i_1_reg_699_pp0_iter1_reg == 6'd57) | ((i_1_reg_699_pp0_iter1_reg == 6'd58) | ((i_1_reg_699_pp0_iter1_reg == 6'd59) | ((i_1_reg_699_pp0_iter1_reg == 6'd60) | ((i_1_reg_699_pp0_iter1_reg == 6'd61) | ((i_1_reg_699_pp0_iter1_reg == 6'd62) | (i_1_reg_699_pp0_iter1_reg == 6'd63))))))))))))))))))))))))));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln69_fu_471_p2 = ((ap_sig_allocacmp_i_1 == 6'd40) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 8'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 1'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign trunc_ln71_fu_488_p1 = m_axi_gmem0_RDATA[0:0];

endmodule //Autoencoder_Autoencoder_Pipeline_VITIS_LOOP_69_4
