-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Autoencoder_Autoencoder_Pipeline_VITIS_LOOP_69_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    DecWeights : IN STD_LOGIC_VECTOR (63 downto 0);
    DecoderWeights_V_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_1_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_2_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_2_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_3_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_3_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_4_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_4_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_5_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_5_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_6_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_6_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_7_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_7_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_8_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_8_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_9_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_9_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_10_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_10_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_11_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_11_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_12_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_12_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_13_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_13_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_14_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_14_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_15_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_15_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_16_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_16_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_17_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_17_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_18_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_18_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_19_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_19_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_20_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_20_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_21_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_21_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_22_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_22_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_23_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_23_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_24_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_24_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_25_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_25_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_26_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_26_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_27_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_27_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_28_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_28_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_29_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_29_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_30_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_30_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_31_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_31_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_32_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_32_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_33_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_33_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_34_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_34_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_35_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_35_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_36_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_36_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_37_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_37_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_38_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_38_out_ap_vld : OUT STD_LOGIC;
    DecoderWeights_V_39_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    DecoderWeights_V_39_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of Autoencoder_Autoencoder_Pipeline_VITIS_LOOP_69_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv6_3D : STD_LOGIC_VECTOR (5 downto 0) := "111101";
    constant ap_const_lv6_3C : STD_LOGIC_VECTOR (5 downto 0) := "111100";
    constant ap_const_lv6_3B : STD_LOGIC_VECTOR (5 downto 0) := "111011";
    constant ap_const_lv6_3A : STD_LOGIC_VECTOR (5 downto 0) := "111010";
    constant ap_const_lv6_39 : STD_LOGIC_VECTOR (5 downto 0) := "111001";
    constant ap_const_lv6_38 : STD_LOGIC_VECTOR (5 downto 0) := "111000";
    constant ap_const_lv6_37 : STD_LOGIC_VECTOR (5 downto 0) := "110111";
    constant ap_const_lv6_36 : STD_LOGIC_VECTOR (5 downto 0) := "110110";
    constant ap_const_lv6_35 : STD_LOGIC_VECTOR (5 downto 0) := "110101";
    constant ap_const_lv6_34 : STD_LOGIC_VECTOR (5 downto 0) := "110100";
    constant ap_const_lv6_33 : STD_LOGIC_VECTOR (5 downto 0) := "110011";
    constant ap_const_lv6_32 : STD_LOGIC_VECTOR (5 downto 0) := "110010";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv6_30 : STD_LOGIC_VECTOR (5 downto 0) := "110000";
    constant ap_const_lv6_2F : STD_LOGIC_VECTOR (5 downto 0) := "101111";
    constant ap_const_lv6_2E : STD_LOGIC_VECTOR (5 downto 0) := "101110";
    constant ap_const_lv6_2D : STD_LOGIC_VECTOR (5 downto 0) := "101101";
    constant ap_const_lv6_2C : STD_LOGIC_VECTOR (5 downto 0) := "101100";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_lv6_3 : STD_LOGIC_VECTOR (5 downto 0) := "000011";
    constant ap_const_lv6_4 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_const_lv6_5 : STD_LOGIC_VECTOR (5 downto 0) := "000101";
    constant ap_const_lv6_6 : STD_LOGIC_VECTOR (5 downto 0) := "000110";
    constant ap_const_lv6_7 : STD_LOGIC_VECTOR (5 downto 0) := "000111";
    constant ap_const_lv6_8 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_const_lv6_9 : STD_LOGIC_VECTOR (5 downto 0) := "001001";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv6_D : STD_LOGIC_VECTOR (5 downto 0) := "001101";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_11 : STD_LOGIC_VECTOR (5 downto 0) := "010001";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_14 : STD_LOGIC_VECTOR (5 downto 0) := "010100";
    constant ap_const_lv6_15 : STD_LOGIC_VECTOR (5 downto 0) := "010101";
    constant ap_const_lv6_16 : STD_LOGIC_VECTOR (5 downto 0) := "010110";
    constant ap_const_lv6_17 : STD_LOGIC_VECTOR (5 downto 0) := "010111";
    constant ap_const_lv6_18 : STD_LOGIC_VECTOR (5 downto 0) := "011000";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1A : STD_LOGIC_VECTOR (5 downto 0) := "011010";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_1D : STD_LOGIC_VECTOR (5 downto 0) := "011101";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_21 : STD_LOGIC_VECTOR (5 downto 0) := "100001";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_25 : STD_LOGIC_VECTOR (5 downto 0) := "100101";
    constant ap_const_lv6_26 : STD_LOGIC_VECTOR (5 downto 0) := "100110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln69_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_1_reg_699 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_reg_699_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln71_fu_488_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln71_reg_712 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_202 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln69_fu_477_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_588 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component Autoencoder_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component Autoencoder_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln69_fu_471_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_202 <= add_ln69_fu_477_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_202 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                i_1_reg_699 <= ap_sig_allocacmp_i_1;
                i_1_reg_699_pp0_iter1_reg <= i_1_reg_699;
                trunc_ln71_reg_712 <= trunc_ln71_fu_488_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    DecoderWeights_V_10_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_10_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_9))) then 
                DecoderWeights_V_10_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_10_out <= "X";
            end if;
        else 
            DecoderWeights_V_10_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_10_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_9)))) then 
            DecoderWeights_V_10_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_10_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_11_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_11_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_A))) then 
                DecoderWeights_V_11_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_11_out <= "X";
            end if;
        else 
            DecoderWeights_V_11_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_11_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_A)))) then 
            DecoderWeights_V_11_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_11_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_12_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_12_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_B))) then 
                DecoderWeights_V_12_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_12_out <= "X";
            end if;
        else 
            DecoderWeights_V_12_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_B)))) then 
            DecoderWeights_V_12_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_13_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_13_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_C))) then 
                DecoderWeights_V_13_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_13_out <= "X";
            end if;
        else 
            DecoderWeights_V_13_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_C)))) then 
            DecoderWeights_V_13_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_14_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_14_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_D))) then 
                DecoderWeights_V_14_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_14_out <= "X";
            end if;
        else 
            DecoderWeights_V_14_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_D)))) then 
            DecoderWeights_V_14_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_15_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_15_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_E))) then 
                DecoderWeights_V_15_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_15_out <= "X";
            end if;
        else 
            DecoderWeights_V_15_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_E)))) then 
            DecoderWeights_V_15_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_16_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_16_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_F))) then 
                DecoderWeights_V_16_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_16_out <= "X";
            end if;
        else 
            DecoderWeights_V_16_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_F)))) then 
            DecoderWeights_V_16_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_17_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_17_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_10))) then 
                DecoderWeights_V_17_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_17_out <= "X";
            end if;
        else 
            DecoderWeights_V_17_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_10)))) then 
            DecoderWeights_V_17_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_18_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_18_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_11))) then 
                DecoderWeights_V_18_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_18_out <= "X";
            end if;
        else 
            DecoderWeights_V_18_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_18_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_11)))) then 
            DecoderWeights_V_18_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_18_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_19_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_19_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_12))) then 
                DecoderWeights_V_19_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_19_out <= "X";
            end if;
        else 
            DecoderWeights_V_19_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_19_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_12)))) then 
            DecoderWeights_V_19_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_1_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_1_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_0))) then 
                DecoderWeights_V_1_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_1_out <= "X";
            end if;
        else 
            DecoderWeights_V_1_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_0)))) then 
            DecoderWeights_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_20_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_20_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_13))) then 
                DecoderWeights_V_20_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_20_out <= "X";
            end if;
        else 
            DecoderWeights_V_20_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_20_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_13)))) then 
            DecoderWeights_V_20_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_20_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_21_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_21_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_14))) then 
                DecoderWeights_V_21_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_21_out <= "X";
            end if;
        else 
            DecoderWeights_V_21_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_21_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_14)))) then 
            DecoderWeights_V_21_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_21_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_22_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_22_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_15))) then 
                DecoderWeights_V_22_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_22_out <= "X";
            end if;
        else 
            DecoderWeights_V_22_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_15)))) then 
            DecoderWeights_V_22_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_23_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_23_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_16))) then 
                DecoderWeights_V_23_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_23_out <= "X";
            end if;
        else 
            DecoderWeights_V_23_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_23_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_16)))) then 
            DecoderWeights_V_23_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_23_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_24_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_24_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_17))) then 
                DecoderWeights_V_24_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_24_out <= "X";
            end if;
        else 
            DecoderWeights_V_24_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_24_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_17)))) then 
            DecoderWeights_V_24_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_24_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_25_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_25_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_18))) then 
                DecoderWeights_V_25_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_25_out <= "X";
            end if;
        else 
            DecoderWeights_V_25_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_25_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_18)))) then 
            DecoderWeights_V_25_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_25_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_26_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_26_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_19))) then 
                DecoderWeights_V_26_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_26_out <= "X";
            end if;
        else 
            DecoderWeights_V_26_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_26_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_19)))) then 
            DecoderWeights_V_26_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_26_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_27_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_27_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1A))) then 
                DecoderWeights_V_27_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_27_out <= "X";
            end if;
        else 
            DecoderWeights_V_27_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_27_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1A)))) then 
            DecoderWeights_V_27_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_27_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_28_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_28_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1B))) then 
                DecoderWeights_V_28_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_28_out <= "X";
            end if;
        else 
            DecoderWeights_V_28_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_28_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1B)))) then 
            DecoderWeights_V_28_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_28_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_29_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_29_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1C))) then 
                DecoderWeights_V_29_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_29_out <= "X";
            end if;
        else 
            DecoderWeights_V_29_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_29_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1C)))) then 
            DecoderWeights_V_29_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_29_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_2_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_2_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1))) then 
                DecoderWeights_V_2_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_2_out <= "X";
            end if;
        else 
            DecoderWeights_V_2_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_2_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1)))) then 
            DecoderWeights_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_30_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_30_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1D))) then 
                DecoderWeights_V_30_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_30_out <= "X";
            end if;
        else 
            DecoderWeights_V_30_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_30_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1D)))) then 
            DecoderWeights_V_30_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_30_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_31_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_31_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1E))) then 
                DecoderWeights_V_31_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_31_out <= "X";
            end if;
        else 
            DecoderWeights_V_31_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_31_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1E)))) then 
            DecoderWeights_V_31_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_31_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_32_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_32_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1F))) then 
                DecoderWeights_V_32_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_32_out <= "X";
            end if;
        else 
            DecoderWeights_V_32_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_32_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_1F)))) then 
            DecoderWeights_V_32_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_32_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_33_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_33_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_20))) then 
                DecoderWeights_V_33_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_33_out <= "X";
            end if;
        else 
            DecoderWeights_V_33_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_33_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_20)))) then 
            DecoderWeights_V_33_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_33_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_34_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_34_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_21))) then 
                DecoderWeights_V_34_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_34_out <= "X";
            end if;
        else 
            DecoderWeights_V_34_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_34_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_21)))) then 
            DecoderWeights_V_34_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_34_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_35_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_35_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_22))) then 
                DecoderWeights_V_35_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_35_out <= "X";
            end if;
        else 
            DecoderWeights_V_35_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_35_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_22)))) then 
            DecoderWeights_V_35_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_35_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_36_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_36_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_23))) then 
                DecoderWeights_V_36_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_36_out <= "X";
            end if;
        else 
            DecoderWeights_V_36_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_36_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_23)))) then 
            DecoderWeights_V_36_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_36_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_37_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_37_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_24))) then 
                DecoderWeights_V_37_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_37_out <= "X";
            end if;
        else 
            DecoderWeights_V_37_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_37_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_24)))) then 
            DecoderWeights_V_37_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_37_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_38_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_38_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_25))) then 
                DecoderWeights_V_38_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_38_out <= "X";
            end if;
        else 
            DecoderWeights_V_38_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_38_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_25)))) then 
            DecoderWeights_V_38_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_38_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_39_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_39_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_26))) then 
                DecoderWeights_V_39_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_39_out <= "X";
            end if;
        else 
            DecoderWeights_V_39_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_39_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_26)))) then 
            DecoderWeights_V_39_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_39_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_3_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_3_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2))) then 
                DecoderWeights_V_3_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_3_out <= "X";
            end if;
        else 
            DecoderWeights_V_3_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2)))) then 
            DecoderWeights_V_3_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_4_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_4_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3))) then 
                DecoderWeights_V_4_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_4_out <= "X";
            end if;
        else 
            DecoderWeights_V_4_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3)))) then 
            DecoderWeights_V_4_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_5_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_5_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_4))) then 
                DecoderWeights_V_5_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_5_out <= "X";
            end if;
        else 
            DecoderWeights_V_5_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_5_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_4)))) then 
            DecoderWeights_V_5_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_6_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_6_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_5))) then 
                DecoderWeights_V_6_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_6_out <= "X";
            end if;
        else 
            DecoderWeights_V_6_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_6_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_5)))) then 
            DecoderWeights_V_6_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_6_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_7_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_7_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_6))) then 
                DecoderWeights_V_7_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_7_out <= "X";
            end if;
        else 
            DecoderWeights_V_7_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_7_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_6)))) then 
            DecoderWeights_V_7_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_8_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_8_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_7))) then 
                DecoderWeights_V_8_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_8_out <= "X";
            end if;
        else 
            DecoderWeights_V_8_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_8_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_7)))) then 
            DecoderWeights_V_8_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_9_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, i_1_reg_699_pp0_iter1_reg, trunc_ln71_reg_712, ap_loop_init)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_9_out <= ap_const_lv1_0;
            elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_8))) then 
                DecoderWeights_V_9_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_9_out <= "X";
            end if;
        else 
            DecoderWeights_V_9_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_9_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_8)))) then 
            DecoderWeights_V_9_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    DecoderWeights_V_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, trunc_ln71_reg_712, ap_loop_init, ap_condition_588)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0)) then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                DecoderWeights_V_out <= ap_const_lv1_0;
            elsif ((ap_const_boolean_1 = ap_condition_588)) then 
                DecoderWeights_V_out <= trunc_ln71_reg_712;
            else 
                DecoderWeights_V_out <= "X";
            end if;
        else 
            DecoderWeights_V_out <= "X";
        end if; 
    end process;


    DecoderWeights_V_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, i_1_reg_699_pp0_iter1_reg, ap_loop_init)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_27) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_28) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_29) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2A) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2B) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2C) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2D) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2E) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2F) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_30) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_31) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_32) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_33) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_34) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_35) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_36) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_37) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_38) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_39) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3A) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3B) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3C) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3D) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3E) or (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3F)))))))))))))))))))))))))))) then 
            DecoderWeights_V_out_ap_vld <= ap_const_logic_1;
        else 
            DecoderWeights_V_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln69_fu_477_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_gmem0_RVALID)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (m_axi_gmem0_RVALID = ap_const_logic_0);
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_588_assign_proc : process(ap_enable_reg_pp0_iter2, i_1_reg_699_pp0_iter1_reg)
    begin
                ap_condition_588 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_27) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_28) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_29) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2A) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2B) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2C) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2D) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2E) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_2F) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_30) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_31) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_32) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_33) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_34) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_35) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_36) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_37) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_38) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_39) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3A) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3B) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3C) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3D) or ((i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3E) or (i_1_reg_699_pp0_iter1_reg = ap_const_lv6_3F))))))))))))))))))))))))));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln69_fu_471_p2)
    begin
        if (((icmp_ln69_fu_471_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_202)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_202;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem0_RVALID, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln69_fu_471_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv6_28) else "0";
    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    trunc_ln71_fu_488_p1 <= m_axi_gmem0_RDATA(1 - 1 downto 0);
end behav;
