// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Autoencoder_BackPropagateDecoderWeightChanges (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        DecoderWeightChanges_address0,
        DecoderWeightChanges_ce0,
        DecoderWeightChanges_we0,
        DecoderWeightChanges_d0,
        Deltas_address0,
        Deltas_ce0,
        Deltas_we0,
        Deltas_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [5:0] DecoderWeightChanges_address0;
output   DecoderWeightChanges_ce0;
output   DecoderWeightChanges_we0;
output  [0:0] DecoderWeightChanges_d0;
output  [1:0] Deltas_address0;
output   Deltas_ce0;
output   Deltas_we0;
output  [0:0] Deltas_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Deltas_ce0;
reg Deltas_we0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] tmp_6_fu_82_p4;
reg   [4:0] tmp_6_reg_108;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln236_fu_61_p2;
wire    grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start;
wire    grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_done;
wire    grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_idle;
wire    grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_ready;
wire   [5:0] grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_address0;
wire    grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_ce0;
wire    grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_we0;
wire   [0:0] grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_d0;
reg    grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln236_fu_73_p1;
reg   [2:0] d_fu_28;
wire   [2:0] add_ln236_fu_67_p2;
reg    ap_block_state1;
wire   [1:0] empty_51_fu_78_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start_reg = 1'b0;
end

Autoencoder_BackPropagateDecoderWeightChanges_Pipeline_Loop31 grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start),
    .ap_done(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_done),
    .ap_idle(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_idle),
    .ap_ready(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_ready),
    .zext_ln247(tmp_6_reg_108),
    .DecoderWeightChanges_address0(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_address0),
    .DecoderWeightChanges_ce0(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_ce0),
    .DecoderWeightChanges_we0(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_we0),
    .DecoderWeightChanges_d0(grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln236_fu_61_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln236_fu_61_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start_reg <= 1'b1;
        end else if ((grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_ready == 1'b1)) begin
            grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        d_fu_28 <= 3'd0;
    end else if (((icmp_ln236_fu_61_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        d_fu_28 <= add_ln236_fu_67_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln236_fu_61_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_6_reg_108[4 : 1] <= tmp_6_fu_82_p4[4 : 1];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Deltas_ce0 = 1'b1;
    end else begin
        Deltas_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_61_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        Deltas_we0 = 1'b1;
    end else begin
        Deltas_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_61_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln236_fu_61_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln236_fu_61_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DecoderWeightChanges_address0 = grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_address0;

assign DecoderWeightChanges_ce0 = grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_ce0;

assign DecoderWeightChanges_d0 = grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_d0;

assign DecoderWeightChanges_we0 = grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_DecoderWeightChanges_we0;

assign Deltas_address0 = zext_ln236_fu_73_p1;

assign Deltas_d0 = 1'd0;

assign add_ln236_fu_67_p2 = (d_fu_28 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_51_fu_78_p1 = d_fu_28[1:0];

assign grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start = grp_BackPropagateDecoderWeightChanges_Pipeline_Loop31_fu_46_ap_start_reg;

assign icmp_ln236_fu_61_p2 = ((d_fu_28 == 3'd4) ? 1'b1 : 1'b0);

assign tmp_6_fu_82_p4 = {{{empty_51_fu_78_p1}, {empty_51_fu_78_p1}}, {1'd0}};

assign zext_ln236_fu_73_p1 = d_fu_28;

always @ (posedge ap_clk) begin
    tmp_6_reg_108[0] <= 1'b0;
end

endmodule //Autoencoder_BackPropagateDecoderWeightChanges
