// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Autoencoder_BackPropagateDecoderWeights (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        DecoderWeights_0_out,
        DecoderWeights_0_out_ap_vld,
        p_read1,
        DecoderWeights_1_out,
        DecoderWeights_1_out_ap_vld,
        p_read2,
        DecoderWeights_2_out,
        DecoderWeights_2_out_ap_vld,
        p_read3,
        DecoderWeights_3_out,
        DecoderWeights_3_out_ap_vld,
        p_read4,
        DecoderWeights_4_out,
        DecoderWeights_4_out_ap_vld,
        p_read5,
        DecoderWeights_5_out,
        DecoderWeights_5_out_ap_vld,
        p_read6,
        DecoderWeights_6_out,
        DecoderWeights_6_out_ap_vld,
        p_read7,
        DecoderWeights_7_out,
        DecoderWeights_7_out_ap_vld,
        p_read8,
        DecoderWeights_8_out,
        DecoderWeights_8_out_ap_vld,
        p_read9,
        DecoderWeights_9_out,
        DecoderWeights_9_out_ap_vld,
        p_read10,
        DecoderWeights_10_out,
        DecoderWeights_10_out_ap_vld,
        p_read11,
        DecoderWeights_11_out,
        DecoderWeights_11_out_ap_vld,
        p_read12,
        DecoderWeights_12_out,
        DecoderWeights_12_out_ap_vld,
        p_read13,
        DecoderWeights_13_out,
        DecoderWeights_13_out_ap_vld,
        p_read14,
        DecoderWeights_14_out,
        DecoderWeights_14_out_ap_vld,
        p_read15,
        DecoderWeights_15_out,
        DecoderWeights_15_out_ap_vld,
        p_read16,
        DecoderWeights_16_out,
        DecoderWeights_16_out_ap_vld,
        p_read17,
        DecoderWeights_17_out,
        DecoderWeights_17_out_ap_vld,
        p_read18,
        DecoderWeights_18_out,
        DecoderWeights_18_out_ap_vld,
        p_read19,
        DecoderWeights_19_out,
        DecoderWeights_19_out_ap_vld,
        p_read20,
        DecoderWeights_20_out,
        DecoderWeights_20_out_ap_vld,
        p_read21,
        DecoderWeights_21_out,
        DecoderWeights_21_out_ap_vld,
        p_read22,
        DecoderWeights_22_out,
        DecoderWeights_22_out_ap_vld,
        p_read23,
        DecoderWeights_23_out,
        DecoderWeights_23_out_ap_vld,
        p_read24,
        DecoderWeights_24_out,
        DecoderWeights_24_out_ap_vld,
        p_read25,
        DecoderWeights_25_out,
        DecoderWeights_25_out_ap_vld,
        p_read26,
        DecoderWeights_26_out,
        DecoderWeights_26_out_ap_vld,
        p_read27,
        DecoderWeights_27_out,
        DecoderWeights_27_out_ap_vld,
        p_read28,
        DecoderWeights_28_out,
        DecoderWeights_28_out_ap_vld,
        p_read29,
        DecoderWeights_29_out,
        DecoderWeights_29_out_ap_vld,
        p_read30,
        DecoderWeights_30_out,
        DecoderWeights_30_out_ap_vld,
        p_read31,
        DecoderWeights_31_out,
        DecoderWeights_31_out_ap_vld,
        p_read32,
        DecoderWeights_32_out,
        DecoderWeights_32_out_ap_vld,
        p_read33,
        DecoderWeights_33_out,
        DecoderWeights_33_out_ap_vld,
        p_read34,
        DecoderWeights_34_out,
        DecoderWeights_34_out_ap_vld,
        p_read35,
        DecoderWeights_35_out,
        DecoderWeights_35_out_ap_vld,
        p_read36,
        DecoderWeights_36_out,
        DecoderWeights_36_out_ap_vld,
        p_read37,
        DecoderWeights_37_out,
        DecoderWeights_37_out_ap_vld,
        p_read38,
        DecoderWeights_38_out,
        DecoderWeights_38_out_ap_vld,
        p_read39,
        DecoderWeights_39_out,
        DecoderWeights_39_out_ap_vld,
        PrevDecoderWeightChanges_address0,
        PrevDecoderWeightChanges_ce0,
        PrevDecoderWeightChanges_we0,
        PrevDecoderWeightChanges_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] p_read;
output  [0:0] DecoderWeights_0_out;
output   DecoderWeights_0_out_ap_vld;
input  [0:0] p_read1;
output  [0:0] DecoderWeights_1_out;
output   DecoderWeights_1_out_ap_vld;
input  [0:0] p_read2;
output  [0:0] DecoderWeights_2_out;
output   DecoderWeights_2_out_ap_vld;
input  [0:0] p_read3;
output  [0:0] DecoderWeights_3_out;
output   DecoderWeights_3_out_ap_vld;
input  [0:0] p_read4;
output  [0:0] DecoderWeights_4_out;
output   DecoderWeights_4_out_ap_vld;
input  [0:0] p_read5;
output  [0:0] DecoderWeights_5_out;
output   DecoderWeights_5_out_ap_vld;
input  [0:0] p_read6;
output  [0:0] DecoderWeights_6_out;
output   DecoderWeights_6_out_ap_vld;
input  [0:0] p_read7;
output  [0:0] DecoderWeights_7_out;
output   DecoderWeights_7_out_ap_vld;
input  [0:0] p_read8;
output  [0:0] DecoderWeights_8_out;
output   DecoderWeights_8_out_ap_vld;
input  [0:0] p_read9;
output  [0:0] DecoderWeights_9_out;
output   DecoderWeights_9_out_ap_vld;
input  [0:0] p_read10;
output  [0:0] DecoderWeights_10_out;
output   DecoderWeights_10_out_ap_vld;
input  [0:0] p_read11;
output  [0:0] DecoderWeights_11_out;
output   DecoderWeights_11_out_ap_vld;
input  [0:0] p_read12;
output  [0:0] DecoderWeights_12_out;
output   DecoderWeights_12_out_ap_vld;
input  [0:0] p_read13;
output  [0:0] DecoderWeights_13_out;
output   DecoderWeights_13_out_ap_vld;
input  [0:0] p_read14;
output  [0:0] DecoderWeights_14_out;
output   DecoderWeights_14_out_ap_vld;
input  [0:0] p_read15;
output  [0:0] DecoderWeights_15_out;
output   DecoderWeights_15_out_ap_vld;
input  [0:0] p_read16;
output  [0:0] DecoderWeights_16_out;
output   DecoderWeights_16_out_ap_vld;
input  [0:0] p_read17;
output  [0:0] DecoderWeights_17_out;
output   DecoderWeights_17_out_ap_vld;
input  [0:0] p_read18;
output  [0:0] DecoderWeights_18_out;
output   DecoderWeights_18_out_ap_vld;
input  [0:0] p_read19;
output  [0:0] DecoderWeights_19_out;
output   DecoderWeights_19_out_ap_vld;
input  [0:0] p_read20;
output  [0:0] DecoderWeights_20_out;
output   DecoderWeights_20_out_ap_vld;
input  [0:0] p_read21;
output  [0:0] DecoderWeights_21_out;
output   DecoderWeights_21_out_ap_vld;
input  [0:0] p_read22;
output  [0:0] DecoderWeights_22_out;
output   DecoderWeights_22_out_ap_vld;
input  [0:0] p_read23;
output  [0:0] DecoderWeights_23_out;
output   DecoderWeights_23_out_ap_vld;
input  [0:0] p_read24;
output  [0:0] DecoderWeights_24_out;
output   DecoderWeights_24_out_ap_vld;
input  [0:0] p_read25;
output  [0:0] DecoderWeights_25_out;
output   DecoderWeights_25_out_ap_vld;
input  [0:0] p_read26;
output  [0:0] DecoderWeights_26_out;
output   DecoderWeights_26_out_ap_vld;
input  [0:0] p_read27;
output  [0:0] DecoderWeights_27_out;
output   DecoderWeights_27_out_ap_vld;
input  [0:0] p_read28;
output  [0:0] DecoderWeights_28_out;
output   DecoderWeights_28_out_ap_vld;
input  [0:0] p_read29;
output  [0:0] DecoderWeights_29_out;
output   DecoderWeights_29_out_ap_vld;
input  [0:0] p_read30;
output  [0:0] DecoderWeights_30_out;
output   DecoderWeights_30_out_ap_vld;
input  [0:0] p_read31;
output  [0:0] DecoderWeights_31_out;
output   DecoderWeights_31_out_ap_vld;
input  [0:0] p_read32;
output  [0:0] DecoderWeights_32_out;
output   DecoderWeights_32_out_ap_vld;
input  [0:0] p_read33;
output  [0:0] DecoderWeights_33_out;
output   DecoderWeights_33_out_ap_vld;
input  [0:0] p_read34;
output  [0:0] DecoderWeights_34_out;
output   DecoderWeights_34_out_ap_vld;
input  [0:0] p_read35;
output  [0:0] DecoderWeights_35_out;
output   DecoderWeights_35_out_ap_vld;
input  [0:0] p_read36;
output  [0:0] DecoderWeights_36_out;
output   DecoderWeights_36_out_ap_vld;
input  [0:0] p_read37;
output  [0:0] DecoderWeights_37_out;
output   DecoderWeights_37_out_ap_vld;
input  [0:0] p_read38;
output  [0:0] DecoderWeights_38_out;
output   DecoderWeights_38_out_ap_vld;
input  [0:0] p_read39;
output  [0:0] DecoderWeights_39_out;
output   DecoderWeights_39_out_ap_vld;
output  [5:0] PrevDecoderWeightChanges_address0;
output   PrevDecoderWeightChanges_ce0;
output   PrevDecoderWeightChanges_we0;
output  [0:0] PrevDecoderWeightChanges_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] DecoderWeights_0_out;
reg DecoderWeights_0_out_ap_vld;
reg[0:0] DecoderWeights_1_out;
reg DecoderWeights_1_out_ap_vld;
reg[0:0] DecoderWeights_2_out;
reg DecoderWeights_2_out_ap_vld;
reg[0:0] DecoderWeights_3_out;
reg DecoderWeights_3_out_ap_vld;
reg[0:0] DecoderWeights_4_out;
reg DecoderWeights_4_out_ap_vld;
reg[0:0] DecoderWeights_5_out;
reg DecoderWeights_5_out_ap_vld;
reg[0:0] DecoderWeights_6_out;
reg DecoderWeights_6_out_ap_vld;
reg[0:0] DecoderWeights_7_out;
reg DecoderWeights_7_out_ap_vld;
reg[0:0] DecoderWeights_8_out;
reg DecoderWeights_8_out_ap_vld;
reg[0:0] DecoderWeights_9_out;
reg DecoderWeights_9_out_ap_vld;
reg[0:0] DecoderWeights_10_out;
reg DecoderWeights_10_out_ap_vld;
reg[0:0] DecoderWeights_11_out;
reg DecoderWeights_11_out_ap_vld;
reg[0:0] DecoderWeights_12_out;
reg DecoderWeights_12_out_ap_vld;
reg[0:0] DecoderWeights_13_out;
reg DecoderWeights_13_out_ap_vld;
reg[0:0] DecoderWeights_14_out;
reg DecoderWeights_14_out_ap_vld;
reg[0:0] DecoderWeights_15_out;
reg DecoderWeights_15_out_ap_vld;
reg[0:0] DecoderWeights_16_out;
reg DecoderWeights_16_out_ap_vld;
reg[0:0] DecoderWeights_17_out;
reg DecoderWeights_17_out_ap_vld;
reg[0:0] DecoderWeights_18_out;
reg DecoderWeights_18_out_ap_vld;
reg[0:0] DecoderWeights_19_out;
reg DecoderWeights_19_out_ap_vld;
reg[0:0] DecoderWeights_20_out;
reg DecoderWeights_20_out_ap_vld;
reg[0:0] DecoderWeights_21_out;
reg DecoderWeights_21_out_ap_vld;
reg[0:0] DecoderWeights_22_out;
reg DecoderWeights_22_out_ap_vld;
reg[0:0] DecoderWeights_23_out;
reg DecoderWeights_23_out_ap_vld;
reg[0:0] DecoderWeights_24_out;
reg DecoderWeights_24_out_ap_vld;
reg[0:0] DecoderWeights_25_out;
reg DecoderWeights_25_out_ap_vld;
reg[0:0] DecoderWeights_26_out;
reg DecoderWeights_26_out_ap_vld;
reg[0:0] DecoderWeights_27_out;
reg DecoderWeights_27_out_ap_vld;
reg[0:0] DecoderWeights_28_out;
reg DecoderWeights_28_out_ap_vld;
reg[0:0] DecoderWeights_29_out;
reg DecoderWeights_29_out_ap_vld;
reg[0:0] DecoderWeights_30_out;
reg DecoderWeights_30_out_ap_vld;
reg[0:0] DecoderWeights_31_out;
reg DecoderWeights_31_out_ap_vld;
reg[0:0] DecoderWeights_32_out;
reg DecoderWeights_32_out_ap_vld;
reg[0:0] DecoderWeights_33_out;
reg DecoderWeights_33_out_ap_vld;
reg[0:0] DecoderWeights_34_out;
reg DecoderWeights_34_out_ap_vld;
reg[0:0] DecoderWeights_35_out;
reg DecoderWeights_35_out_ap_vld;
reg[0:0] DecoderWeights_36_out;
reg DecoderWeights_36_out_ap_vld;
reg[0:0] DecoderWeights_37_out;
reg DecoderWeights_37_out_ap_vld;
reg[0:0] DecoderWeights_38_out;
reg DecoderWeights_38_out_ap_vld;
reg[0:0] DecoderWeights_39_out;
reg DecoderWeights_39_out_ap_vld;
reg PrevDecoderWeightChanges_ce0;
reg PrevDecoderWeightChanges_we0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] add_ln328_fu_1361_p2;
reg   [2:0] add_ln328_reg_2231;
wire    ap_CS_fsm_state2;
wire   [5:0] zext_ln331_fu_1381_p1;
reg   [5:0] zext_ln331_reg_2236;
wire   [0:0] icmp_ln328_fu_1355_p2;
wire   [3:0] add_ln331_fu_1395_p2;
wire    ap_CS_fsm_state3;
reg   [3:0] h_reg_976;
wire   [0:0] icmp_ln331_fu_1389_p2;
wire   [63:0] zext_ln337_fu_1406_p1;
reg   [2:0] d_fu_278;
reg    ap_block_state1;
reg   [0:0] DecoderWeights_0_copy_0_fu_282;
wire   [0:0] tmp_fu_1411_p42;
wire   [5:0] add_ln334_fu_1401_p2;
reg   [0:0] DecoderWeights_1_copy_0_fu_286;
reg   [0:0] DecoderWeights_2_copy_0_fu_290;
reg   [0:0] DecoderWeights_3_copy_0_fu_294;
reg   [0:0] DecoderWeights_4_copy_0_fu_298;
reg   [0:0] DecoderWeights_5_copy_0_fu_302;
reg   [0:0] DecoderWeights_6_copy_0_fu_306;
reg   [0:0] DecoderWeights_7_copy_0_fu_310;
reg   [0:0] DecoderWeights_8_copy_0_fu_314;
reg   [0:0] DecoderWeights_9_copy_0_fu_318;
reg   [0:0] DecoderWeights_10_copy_0_fu_322;
reg   [0:0] DecoderWeights_11_copy_0_fu_326;
reg   [0:0] DecoderWeights_12_copy_0_fu_330;
reg   [0:0] DecoderWeights_13_copy_0_fu_334;
reg   [0:0] DecoderWeights_14_copy_0_fu_338;
reg   [0:0] DecoderWeights_15_copy_0_fu_342;
reg   [0:0] DecoderWeights_16_copy_0_fu_346;
reg   [0:0] DecoderWeights_17_copy_0_fu_350;
reg   [0:0] DecoderWeights_18_copy_0_fu_354;
reg   [0:0] DecoderWeights_19_copy_0_fu_358;
reg   [0:0] DecoderWeights_20_copy_0_fu_362;
reg   [0:0] DecoderWeights_21_copy_0_fu_366;
reg   [0:0] DecoderWeights_22_copy_0_fu_370;
reg   [0:0] DecoderWeights_23_copy_0_fu_374;
reg   [0:0] DecoderWeights_24_copy_0_fu_378;
reg   [0:0] DecoderWeights_25_copy_0_fu_382;
reg   [0:0] DecoderWeights_26_copy_0_fu_386;
reg   [0:0] DecoderWeights_27_copy_0_fu_390;
reg   [0:0] DecoderWeights_28_copy_0_fu_394;
reg   [0:0] DecoderWeights_29_copy_0_fu_398;
reg   [0:0] DecoderWeights_30_copy_0_fu_402;
reg   [0:0] DecoderWeights_31_copy_0_fu_406;
reg   [0:0] DecoderWeights_32_copy_0_fu_410;
reg   [0:0] DecoderWeights_33_copy_0_fu_414;
reg   [0:0] DecoderWeights_34_copy_0_fu_418;
reg   [0:0] DecoderWeights_35_copy_0_fu_422;
reg   [0:0] DecoderWeights_36_copy_0_fu_426;
reg   [0:0] DecoderWeights_37_copy_0_fu_430;
reg   [0:0] DecoderWeights_38_copy_0_fu_434;
reg   [0:0] DecoderWeights_39_copy_0_fu_438;
reg   [0:0] DecoderWeights_0_out_preg;
reg   [0:0] DecoderWeights_1_out_preg;
reg   [0:0] DecoderWeights_2_out_preg;
reg   [0:0] DecoderWeights_3_out_preg;
reg   [0:0] DecoderWeights_4_out_preg;
reg   [0:0] DecoderWeights_5_out_preg;
reg   [0:0] DecoderWeights_6_out_preg;
reg   [0:0] DecoderWeights_7_out_preg;
reg   [0:0] DecoderWeights_8_out_preg;
reg   [0:0] DecoderWeights_9_out_preg;
reg   [0:0] DecoderWeights_10_out_preg;
reg   [0:0] DecoderWeights_11_out_preg;
reg   [0:0] DecoderWeights_12_out_preg;
reg   [0:0] DecoderWeights_13_out_preg;
reg   [0:0] DecoderWeights_14_out_preg;
reg   [0:0] DecoderWeights_15_out_preg;
reg   [0:0] DecoderWeights_16_out_preg;
reg   [0:0] DecoderWeights_17_out_preg;
reg   [0:0] DecoderWeights_18_out_preg;
reg   [0:0] DecoderWeights_19_out_preg;
reg   [0:0] DecoderWeights_20_out_preg;
reg   [0:0] DecoderWeights_21_out_preg;
reg   [0:0] DecoderWeights_22_out_preg;
reg   [0:0] DecoderWeights_23_out_preg;
reg   [0:0] DecoderWeights_24_out_preg;
reg   [0:0] DecoderWeights_25_out_preg;
reg   [0:0] DecoderWeights_26_out_preg;
reg   [0:0] DecoderWeights_27_out_preg;
reg   [0:0] DecoderWeights_28_out_preg;
reg   [0:0] DecoderWeights_29_out_preg;
reg   [0:0] DecoderWeights_30_out_preg;
reg   [0:0] DecoderWeights_31_out_preg;
reg   [0:0] DecoderWeights_32_out_preg;
reg   [0:0] DecoderWeights_33_out_preg;
reg   [0:0] DecoderWeights_34_out_preg;
reg   [0:0] DecoderWeights_35_out_preg;
reg   [0:0] DecoderWeights_36_out_preg;
reg   [0:0] DecoderWeights_37_out_preg;
reg   [0:0] DecoderWeights_38_out_preg;
reg   [0:0] DecoderWeights_39_out_preg;
wire   [1:0] empty_49_fu_1367_p1;
wire   [4:0] tmp_5_fu_1371_p4;
wire   [5:0] zext_ln331_1_fu_1385_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 DecoderWeights_0_out_preg = 1'd0;
#0 DecoderWeights_1_out_preg = 1'd0;
#0 DecoderWeights_2_out_preg = 1'd0;
#0 DecoderWeights_3_out_preg = 1'd0;
#0 DecoderWeights_4_out_preg = 1'd0;
#0 DecoderWeights_5_out_preg = 1'd0;
#0 DecoderWeights_6_out_preg = 1'd0;
#0 DecoderWeights_7_out_preg = 1'd0;
#0 DecoderWeights_8_out_preg = 1'd0;
#0 DecoderWeights_9_out_preg = 1'd0;
#0 DecoderWeights_10_out_preg = 1'd0;
#0 DecoderWeights_11_out_preg = 1'd0;
#0 DecoderWeights_12_out_preg = 1'd0;
#0 DecoderWeights_13_out_preg = 1'd0;
#0 DecoderWeights_14_out_preg = 1'd0;
#0 DecoderWeights_15_out_preg = 1'd0;
#0 DecoderWeights_16_out_preg = 1'd0;
#0 DecoderWeights_17_out_preg = 1'd0;
#0 DecoderWeights_18_out_preg = 1'd0;
#0 DecoderWeights_19_out_preg = 1'd0;
#0 DecoderWeights_20_out_preg = 1'd0;
#0 DecoderWeights_21_out_preg = 1'd0;
#0 DecoderWeights_22_out_preg = 1'd0;
#0 DecoderWeights_23_out_preg = 1'd0;
#0 DecoderWeights_24_out_preg = 1'd0;
#0 DecoderWeights_25_out_preg = 1'd0;
#0 DecoderWeights_26_out_preg = 1'd0;
#0 DecoderWeights_27_out_preg = 1'd0;
#0 DecoderWeights_28_out_preg = 1'd0;
#0 DecoderWeights_29_out_preg = 1'd0;
#0 DecoderWeights_30_out_preg = 1'd0;
#0 DecoderWeights_31_out_preg = 1'd0;
#0 DecoderWeights_32_out_preg = 1'd0;
#0 DecoderWeights_33_out_preg = 1'd0;
#0 DecoderWeights_34_out_preg = 1'd0;
#0 DecoderWeights_35_out_preg = 1'd0;
#0 DecoderWeights_36_out_preg = 1'd0;
#0 DecoderWeights_37_out_preg = 1'd0;
#0 DecoderWeights_38_out_preg = 1'd0;
#0 DecoderWeights_39_out_preg = 1'd0;
end

Autoencoder_mux_406_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 1 ),
    .din33_WIDTH( 1 ),
    .din34_WIDTH( 1 ),
    .din35_WIDTH( 1 ),
    .din36_WIDTH( 1 ),
    .din37_WIDTH( 1 ),
    .din38_WIDTH( 1 ),
    .din39_WIDTH( 1 ),
    .din40_WIDTH( 6 ),
    .dout_WIDTH( 1 ))
mux_406_1_1_1_U180(
    .din0(DecoderWeights_0_copy_0_fu_282),
    .din1(DecoderWeights_1_copy_0_fu_286),
    .din2(DecoderWeights_2_copy_0_fu_290),
    .din3(DecoderWeights_3_copy_0_fu_294),
    .din4(DecoderWeights_4_copy_0_fu_298),
    .din5(DecoderWeights_5_copy_0_fu_302),
    .din6(DecoderWeights_6_copy_0_fu_306),
    .din7(DecoderWeights_7_copy_0_fu_310),
    .din8(DecoderWeights_8_copy_0_fu_314),
    .din9(DecoderWeights_9_copy_0_fu_318),
    .din10(DecoderWeights_10_copy_0_fu_322),
    .din11(DecoderWeights_11_copy_0_fu_326),
    .din12(DecoderWeights_12_copy_0_fu_330),
    .din13(DecoderWeights_13_copy_0_fu_334),
    .din14(DecoderWeights_14_copy_0_fu_338),
    .din15(DecoderWeights_15_copy_0_fu_342),
    .din16(DecoderWeights_16_copy_0_fu_346),
    .din17(DecoderWeights_17_copy_0_fu_350),
    .din18(DecoderWeights_18_copy_0_fu_354),
    .din19(DecoderWeights_19_copy_0_fu_358),
    .din20(DecoderWeights_20_copy_0_fu_362),
    .din21(DecoderWeights_21_copy_0_fu_366),
    .din22(DecoderWeights_22_copy_0_fu_370),
    .din23(DecoderWeights_23_copy_0_fu_374),
    .din24(DecoderWeights_24_copy_0_fu_378),
    .din25(DecoderWeights_25_copy_0_fu_382),
    .din26(DecoderWeights_26_copy_0_fu_386),
    .din27(DecoderWeights_27_copy_0_fu_390),
    .din28(DecoderWeights_28_copy_0_fu_394),
    .din29(DecoderWeights_29_copy_0_fu_398),
    .din30(DecoderWeights_30_copy_0_fu_402),
    .din31(DecoderWeights_31_copy_0_fu_406),
    .din32(DecoderWeights_32_copy_0_fu_410),
    .din33(DecoderWeights_33_copy_0_fu_414),
    .din34(DecoderWeights_34_copy_0_fu_418),
    .din35(DecoderWeights_35_copy_0_fu_422),
    .din36(DecoderWeights_36_copy_0_fu_426),
    .din37(DecoderWeights_37_copy_0_fu_430),
    .din38(DecoderWeights_38_copy_0_fu_434),
    .din39(DecoderWeights_39_copy_0_fu_438),
    .din40(add_ln334_fu_1401_p2),
    .dout(tmp_fu_1411_p42)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_0_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_0_out_preg <= DecoderWeights_0_copy_0_fu_282;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_10_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_10_out_preg <= DecoderWeights_10_copy_0_fu_322;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_11_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_11_out_preg <= DecoderWeights_11_copy_0_fu_326;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_12_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_12_out_preg <= DecoderWeights_12_copy_0_fu_330;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_13_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_13_out_preg <= DecoderWeights_13_copy_0_fu_334;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_14_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_14_out_preg <= DecoderWeights_14_copy_0_fu_338;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_15_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_15_out_preg <= DecoderWeights_15_copy_0_fu_342;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_16_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_16_out_preg <= DecoderWeights_16_copy_0_fu_346;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_17_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_17_out_preg <= DecoderWeights_17_copy_0_fu_350;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_18_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_18_out_preg <= DecoderWeights_18_copy_0_fu_354;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_19_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_19_out_preg <= DecoderWeights_19_copy_0_fu_358;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_1_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_1_out_preg <= DecoderWeights_1_copy_0_fu_286;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_20_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_20_out_preg <= DecoderWeights_20_copy_0_fu_362;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_21_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_21_out_preg <= DecoderWeights_21_copy_0_fu_366;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_22_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_22_out_preg <= DecoderWeights_22_copy_0_fu_370;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_23_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_23_out_preg <= DecoderWeights_23_copy_0_fu_374;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_24_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_24_out_preg <= DecoderWeights_24_copy_0_fu_378;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_25_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_25_out_preg <= DecoderWeights_25_copy_0_fu_382;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_26_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_26_out_preg <= DecoderWeights_26_copy_0_fu_386;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_27_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_27_out_preg <= DecoderWeights_27_copy_0_fu_390;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_28_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_28_out_preg <= DecoderWeights_28_copy_0_fu_394;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_29_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_29_out_preg <= DecoderWeights_29_copy_0_fu_398;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_2_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_2_out_preg <= DecoderWeights_2_copy_0_fu_290;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_30_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_30_out_preg <= DecoderWeights_30_copy_0_fu_402;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_31_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_31_out_preg <= DecoderWeights_31_copy_0_fu_406;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_32_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_32_out_preg <= DecoderWeights_32_copy_0_fu_410;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_33_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_33_out_preg <= DecoderWeights_33_copy_0_fu_414;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_34_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_34_out_preg <= DecoderWeights_34_copy_0_fu_418;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_35_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_35_out_preg <= DecoderWeights_35_copy_0_fu_422;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_36_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_36_out_preg <= DecoderWeights_36_copy_0_fu_426;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_37_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_37_out_preg <= DecoderWeights_37_copy_0_fu_430;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_38_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_38_out_preg <= DecoderWeights_38_copy_0_fu_434;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_39_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_39_out_preg <= DecoderWeights_39_copy_0_fu_438;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_3_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_3_out_preg <= DecoderWeights_3_copy_0_fu_294;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_4_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_4_out_preg <= DecoderWeights_4_copy_0_fu_298;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_5_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_5_out_preg <= DecoderWeights_5_copy_0_fu_302;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_6_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_6_out_preg <= DecoderWeights_6_copy_0_fu_306;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_7_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_7_out_preg <= DecoderWeights_7_copy_0_fu_310;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_8_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_8_out_preg <= DecoderWeights_8_copy_0_fu_314;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        DecoderWeights_9_out_preg <= 1'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            DecoderWeights_9_out_preg <= DecoderWeights_9_copy_0_fu_318;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_0_copy_0_fu_282 <= p_read;
    end else if (((1'b1 == ap_CS_fsm_state3) & (6'd0 == add_ln334_fu_1401_p2) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_0_copy_0_fu_282 <= tmp_fu_1411_p42;
    end else if (((1'b1 == ap_CS_fsm_state3) & (6'd0 == add_ln334_fu_1401_p2) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_0_copy_0_fu_282 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_10_copy_0_fu_322 <= p_read10;
    end else if (((6'd10 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_10_copy_0_fu_322 <= tmp_fu_1411_p42;
    end else if (((6'd10 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_10_copy_0_fu_322 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_11_copy_0_fu_326 <= p_read11;
    end else if (((6'd11 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_11_copy_0_fu_326 <= tmp_fu_1411_p42;
    end else if (((6'd11 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_11_copy_0_fu_326 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_12_copy_0_fu_330 <= p_read12;
    end else if (((6'd12 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_12_copy_0_fu_330 <= tmp_fu_1411_p42;
    end else if (((6'd12 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_12_copy_0_fu_330 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_13_copy_0_fu_334 <= p_read13;
    end else if (((6'd13 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_13_copy_0_fu_334 <= tmp_fu_1411_p42;
    end else if (((6'd13 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_13_copy_0_fu_334 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_14_copy_0_fu_338 <= p_read14;
    end else if (((6'd14 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_14_copy_0_fu_338 <= tmp_fu_1411_p42;
    end else if (((6'd14 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_14_copy_0_fu_338 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_15_copy_0_fu_342 <= p_read15;
    end else if (((6'd15 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_15_copy_0_fu_342 <= tmp_fu_1411_p42;
    end else if (((6'd15 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_15_copy_0_fu_342 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_16_copy_0_fu_346 <= p_read16;
    end else if (((6'd16 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_16_copy_0_fu_346 <= tmp_fu_1411_p42;
    end else if (((6'd16 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_16_copy_0_fu_346 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_17_copy_0_fu_350 <= p_read17;
    end else if (((6'd17 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_17_copy_0_fu_350 <= tmp_fu_1411_p42;
    end else if (((6'd17 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_17_copy_0_fu_350 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_18_copy_0_fu_354 <= p_read18;
    end else if (((6'd18 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_18_copy_0_fu_354 <= tmp_fu_1411_p42;
    end else if (((6'd18 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_18_copy_0_fu_354 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_19_copy_0_fu_358 <= p_read19;
    end else if (((6'd19 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_19_copy_0_fu_358 <= tmp_fu_1411_p42;
    end else if (((6'd19 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_19_copy_0_fu_358 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_1_copy_0_fu_286 <= p_read1;
    end else if (((6'd1 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_1_copy_0_fu_286 <= tmp_fu_1411_p42;
    end else if (((6'd1 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_1_copy_0_fu_286 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_20_copy_0_fu_362 <= p_read20;
    end else if (((6'd20 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_20_copy_0_fu_362 <= tmp_fu_1411_p42;
    end else if (((6'd20 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_20_copy_0_fu_362 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_21_copy_0_fu_366 <= p_read21;
    end else if (((6'd21 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_21_copy_0_fu_366 <= tmp_fu_1411_p42;
    end else if (((6'd21 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_21_copy_0_fu_366 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_22_copy_0_fu_370 <= p_read22;
    end else if (((6'd22 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_22_copy_0_fu_370 <= tmp_fu_1411_p42;
    end else if (((6'd22 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_22_copy_0_fu_370 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_23_copy_0_fu_374 <= p_read23;
    end else if (((6'd23 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_23_copy_0_fu_374 <= tmp_fu_1411_p42;
    end else if (((6'd23 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_23_copy_0_fu_374 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_24_copy_0_fu_378 <= p_read24;
    end else if (((6'd24 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_24_copy_0_fu_378 <= tmp_fu_1411_p42;
    end else if (((6'd24 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_24_copy_0_fu_378 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_25_copy_0_fu_382 <= p_read25;
    end else if (((6'd25 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_25_copy_0_fu_382 <= tmp_fu_1411_p42;
    end else if (((6'd25 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_25_copy_0_fu_382 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_26_copy_0_fu_386 <= p_read26;
    end else if (((6'd26 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_26_copy_0_fu_386 <= tmp_fu_1411_p42;
    end else if (((6'd26 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_26_copy_0_fu_386 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_27_copy_0_fu_390 <= p_read27;
    end else if (((6'd27 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_27_copy_0_fu_390 <= tmp_fu_1411_p42;
    end else if (((6'd27 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_27_copy_0_fu_390 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_28_copy_0_fu_394 <= p_read28;
    end else if (((6'd28 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_28_copy_0_fu_394 <= tmp_fu_1411_p42;
    end else if (((6'd28 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_28_copy_0_fu_394 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_29_copy_0_fu_398 <= p_read29;
    end else if (((6'd29 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_29_copy_0_fu_398 <= tmp_fu_1411_p42;
    end else if (((6'd29 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_29_copy_0_fu_398 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_2_copy_0_fu_290 <= p_read2;
    end else if (((6'd2 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_2_copy_0_fu_290 <= tmp_fu_1411_p42;
    end else if (((6'd2 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_2_copy_0_fu_290 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_30_copy_0_fu_402 <= p_read30;
    end else if (((6'd30 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_30_copy_0_fu_402 <= tmp_fu_1411_p42;
    end else if (((6'd30 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_30_copy_0_fu_402 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_31_copy_0_fu_406 <= p_read31;
    end else if (((6'd31 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_31_copy_0_fu_406 <= tmp_fu_1411_p42;
    end else if (((6'd31 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_31_copy_0_fu_406 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_32_copy_0_fu_410 <= p_read32;
    end else if (((6'd32 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_32_copy_0_fu_410 <= tmp_fu_1411_p42;
    end else if (((6'd32 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_32_copy_0_fu_410 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_33_copy_0_fu_414 <= p_read33;
    end else if (((6'd33 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_33_copy_0_fu_414 <= tmp_fu_1411_p42;
    end else if (((6'd33 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_33_copy_0_fu_414 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_34_copy_0_fu_418 <= p_read34;
    end else if (((6'd34 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_34_copy_0_fu_418 <= tmp_fu_1411_p42;
    end else if (((6'd34 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_34_copy_0_fu_418 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_35_copy_0_fu_422 <= p_read35;
    end else if (((6'd35 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_35_copy_0_fu_422 <= tmp_fu_1411_p42;
    end else if (((6'd35 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_35_copy_0_fu_422 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_36_copy_0_fu_426 <= p_read36;
    end else if (((6'd36 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_36_copy_0_fu_426 <= tmp_fu_1411_p42;
    end else if (((6'd36 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_36_copy_0_fu_426 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_37_copy_0_fu_430 <= p_read37;
    end else if (((6'd37 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_37_copy_0_fu_430 <= tmp_fu_1411_p42;
    end else if (((6'd37 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_37_copy_0_fu_430 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_38_copy_0_fu_434 <= p_read38;
    end else if (((6'd38 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_38_copy_0_fu_434 <= tmp_fu_1411_p42;
    end else if (((6'd38 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_38_copy_0_fu_434 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_39_copy_0_fu_438 <= p_read39;
    end else if ((~(6'd38 == add_ln334_fu_1401_p2) & ~(6'd37 == add_ln334_fu_1401_p2) & ~(6'd36 == add_ln334_fu_1401_p2) & ~(6'd35 == add_ln334_fu_1401_p2) & ~(6'd34 == add_ln334_fu_1401_p2) & ~(6'd33 == add_ln334_fu_1401_p2) & ~(6'd32 == add_ln334_fu_1401_p2) & ~(6'd31 == add_ln334_fu_1401_p2) & ~(6'd30 == add_ln334_fu_1401_p2) & ~(6'd29 == add_ln334_fu_1401_p2) & ~(6'd28 == add_ln334_fu_1401_p2) & ~(6'd27 == add_ln334_fu_1401_p2) & ~(6'd26 == add_ln334_fu_1401_p2) & ~(6'd25 == add_ln334_fu_1401_p2) & ~(6'd24 == add_ln334_fu_1401_p2) & ~(6'd23 == add_ln334_fu_1401_p2) & ~(6'd22 == add_ln334_fu_1401_p2) & ~(6'd21 == add_ln334_fu_1401_p2) & ~(6'd20 == add_ln334_fu_1401_p2) & ~(6'd19 == add_ln334_fu_1401_p2) & ~(6'd18 == add_ln334_fu_1401_p2) & ~(6'd17 == add_ln334_fu_1401_p2) & ~(6'd16 == add_ln334_fu_1401_p2) & ~(6'd15 == add_ln334_fu_1401_p2) & ~(6'd14 == add_ln334_fu_1401_p2) & ~(6'd13 == add_ln334_fu_1401_p2) & ~(6'd12 == add_ln334_fu_1401_p2) & ~(6'd11 == add_ln334_fu_1401_p2) & ~(6'd10 == add_ln334_fu_1401_p2) & ~(6'd9 == add_ln334_fu_1401_p2) & ~(6'd8 == add_ln334_fu_1401_p2) & ~(6'd7 == add_ln334_fu_1401_p2) & ~(6'd6 == add_ln334_fu_1401_p2) & ~(6'd5 == add_ln334_fu_1401_p2) & ~(6'd4 == add_ln334_fu_1401_p2) & ~(6'd3 == add_ln334_fu_1401_p2) & ~(6'd2 == add_ln334_fu_1401_p2) & ~(6'd1 == add_ln334_fu_1401_p2) & ~(6'd0 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_39_copy_0_fu_438 <= tmp_fu_1411_p42;
    end else if ((~(6'd38 == add_ln334_fu_1401_p2) & ~(6'd37 == add_ln334_fu_1401_p2) & ~(6'd36 == add_ln334_fu_1401_p2) & ~(6'd35 == add_ln334_fu_1401_p2) & ~(6'd34 == add_ln334_fu_1401_p2) & ~(6'd33 == add_ln334_fu_1401_p2) & ~(6'd32 == add_ln334_fu_1401_p2) & ~(6'd31 == add_ln334_fu_1401_p2) & ~(6'd30 == add_ln334_fu_1401_p2) & ~(6'd29 == add_ln334_fu_1401_p2) & ~(6'd28 == add_ln334_fu_1401_p2) & ~(6'd27 == add_ln334_fu_1401_p2) & ~(6'd26 == add_ln334_fu_1401_p2) & ~(6'd25 == add_ln334_fu_1401_p2) & ~(6'd24 == add_ln334_fu_1401_p2) & ~(6'd23 == add_ln334_fu_1401_p2) & ~(6'd22 == add_ln334_fu_1401_p2) & ~(6'd21 == add_ln334_fu_1401_p2) & ~(6'd20 == add_ln334_fu_1401_p2) & ~(6'd19 == add_ln334_fu_1401_p2) & ~(6'd18 == add_ln334_fu_1401_p2) & ~(6'd17 == add_ln334_fu_1401_p2) & ~(6'd16 == add_ln334_fu_1401_p2) & ~(6'd15 == add_ln334_fu_1401_p2) & ~(6'd14 == add_ln334_fu_1401_p2) & ~(6'd13 == add_ln334_fu_1401_p2) & ~(6'd12 == add_ln334_fu_1401_p2) & ~(6'd11 == add_ln334_fu_1401_p2) & ~(6'd10 == add_ln334_fu_1401_p2) & ~(6'd9 == add_ln334_fu_1401_p2) & ~(6'd8 == add_ln334_fu_1401_p2) & ~(6'd7 == add_ln334_fu_1401_p2) & ~(6'd6 == add_ln334_fu_1401_p2) & ~(6'd5 == add_ln334_fu_1401_p2) & ~(6'd4 == add_ln334_fu_1401_p2) & ~(6'd3 == add_ln334_fu_1401_p2) & ~(6'd2 == add_ln334_fu_1401_p2) & ~(6'd1 == add_ln334_fu_1401_p2) & ~(6'd0 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_39_copy_0_fu_438 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_3_copy_0_fu_294 <= p_read3;
    end else if (((6'd3 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_3_copy_0_fu_294 <= tmp_fu_1411_p42;
    end else if (((6'd3 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_3_copy_0_fu_294 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_4_copy_0_fu_298 <= p_read4;
    end else if (((6'd4 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_4_copy_0_fu_298 <= tmp_fu_1411_p42;
    end else if (((6'd4 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_4_copy_0_fu_298 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_5_copy_0_fu_302 <= p_read5;
    end else if (((6'd5 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_5_copy_0_fu_302 <= tmp_fu_1411_p42;
    end else if (((6'd5 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_5_copy_0_fu_302 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_6_copy_0_fu_306 <= p_read6;
    end else if (((6'd6 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_6_copy_0_fu_306 <= tmp_fu_1411_p42;
    end else if (((6'd6 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_6_copy_0_fu_306 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_7_copy_0_fu_310 <= p_read7;
    end else if (((6'd7 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_7_copy_0_fu_310 <= tmp_fu_1411_p42;
    end else if (((6'd7 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_7_copy_0_fu_310 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_8_copy_0_fu_314 <= p_read8;
    end else if (((6'd8 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_8_copy_0_fu_314 <= tmp_fu_1411_p42;
    end else if (((6'd8 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_8_copy_0_fu_314 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DecoderWeights_9_copy_0_fu_318 <= p_read9;
    end else if (((6'd9 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_9_copy_0_fu_318 <= tmp_fu_1411_p42;
    end else if (((6'd9 == add_ln334_fu_1401_p2) & (1'b1 == ap_CS_fsm_state3) & (tmp_fu_1411_p42 == 1'd0) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        DecoderWeights_9_copy_0_fu_318 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        d_fu_278 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd1))) begin
        d_fu_278 <= add_ln328_reg_2231;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        h_reg_976 <= add_ln331_fu_1395_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd0))) begin
        h_reg_976 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln328_reg_2231 <= add_ln328_fu_1361_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd0))) begin
        zext_ln331_reg_2236[4 : 1] <= zext_ln331_fu_1381_p1[4 : 1];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_0_out = DecoderWeights_0_copy_0_fu_282;
    end else begin
        DecoderWeights_0_out = DecoderWeights_0_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_0_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_10_out = DecoderWeights_10_copy_0_fu_322;
    end else begin
        DecoderWeights_10_out = DecoderWeights_10_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_10_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_11_out = DecoderWeights_11_copy_0_fu_326;
    end else begin
        DecoderWeights_11_out = DecoderWeights_11_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_11_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_12_out = DecoderWeights_12_copy_0_fu_330;
    end else begin
        DecoderWeights_12_out = DecoderWeights_12_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_12_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_13_out = DecoderWeights_13_copy_0_fu_334;
    end else begin
        DecoderWeights_13_out = DecoderWeights_13_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_13_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_14_out = DecoderWeights_14_copy_0_fu_338;
    end else begin
        DecoderWeights_14_out = DecoderWeights_14_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_14_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_15_out = DecoderWeights_15_copy_0_fu_342;
    end else begin
        DecoderWeights_15_out = DecoderWeights_15_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_15_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_16_out = DecoderWeights_16_copy_0_fu_346;
    end else begin
        DecoderWeights_16_out = DecoderWeights_16_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_16_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_17_out = DecoderWeights_17_copy_0_fu_350;
    end else begin
        DecoderWeights_17_out = DecoderWeights_17_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_17_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_18_out = DecoderWeights_18_copy_0_fu_354;
    end else begin
        DecoderWeights_18_out = DecoderWeights_18_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_18_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_19_out = DecoderWeights_19_copy_0_fu_358;
    end else begin
        DecoderWeights_19_out = DecoderWeights_19_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_19_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_1_out = DecoderWeights_1_copy_0_fu_286;
    end else begin
        DecoderWeights_1_out = DecoderWeights_1_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_1_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_20_out = DecoderWeights_20_copy_0_fu_362;
    end else begin
        DecoderWeights_20_out = DecoderWeights_20_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_20_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_21_out = DecoderWeights_21_copy_0_fu_366;
    end else begin
        DecoderWeights_21_out = DecoderWeights_21_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_21_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_22_out = DecoderWeights_22_copy_0_fu_370;
    end else begin
        DecoderWeights_22_out = DecoderWeights_22_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_22_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_23_out = DecoderWeights_23_copy_0_fu_374;
    end else begin
        DecoderWeights_23_out = DecoderWeights_23_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_23_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_24_out = DecoderWeights_24_copy_0_fu_378;
    end else begin
        DecoderWeights_24_out = DecoderWeights_24_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_24_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_25_out = DecoderWeights_25_copy_0_fu_382;
    end else begin
        DecoderWeights_25_out = DecoderWeights_25_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_25_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_26_out = DecoderWeights_26_copy_0_fu_386;
    end else begin
        DecoderWeights_26_out = DecoderWeights_26_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_26_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_27_out = DecoderWeights_27_copy_0_fu_390;
    end else begin
        DecoderWeights_27_out = DecoderWeights_27_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_27_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_28_out = DecoderWeights_28_copy_0_fu_394;
    end else begin
        DecoderWeights_28_out = DecoderWeights_28_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_28_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_29_out = DecoderWeights_29_copy_0_fu_398;
    end else begin
        DecoderWeights_29_out = DecoderWeights_29_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_29_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_2_out = DecoderWeights_2_copy_0_fu_290;
    end else begin
        DecoderWeights_2_out = DecoderWeights_2_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_2_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_30_out = DecoderWeights_30_copy_0_fu_402;
    end else begin
        DecoderWeights_30_out = DecoderWeights_30_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_30_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_31_out = DecoderWeights_31_copy_0_fu_406;
    end else begin
        DecoderWeights_31_out = DecoderWeights_31_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_31_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_32_out = DecoderWeights_32_copy_0_fu_410;
    end else begin
        DecoderWeights_32_out = DecoderWeights_32_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_32_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_33_out = DecoderWeights_33_copy_0_fu_414;
    end else begin
        DecoderWeights_33_out = DecoderWeights_33_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_33_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_34_out = DecoderWeights_34_copy_0_fu_418;
    end else begin
        DecoderWeights_34_out = DecoderWeights_34_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_34_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_35_out = DecoderWeights_35_copy_0_fu_422;
    end else begin
        DecoderWeights_35_out = DecoderWeights_35_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_35_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_36_out = DecoderWeights_36_copy_0_fu_426;
    end else begin
        DecoderWeights_36_out = DecoderWeights_36_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_36_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_37_out = DecoderWeights_37_copy_0_fu_430;
    end else begin
        DecoderWeights_37_out = DecoderWeights_37_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_37_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_38_out = DecoderWeights_38_copy_0_fu_434;
    end else begin
        DecoderWeights_38_out = DecoderWeights_38_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_38_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_39_out = DecoderWeights_39_copy_0_fu_438;
    end else begin
        DecoderWeights_39_out = DecoderWeights_39_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_39_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_3_out = DecoderWeights_3_copy_0_fu_294;
    end else begin
        DecoderWeights_3_out = DecoderWeights_3_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_3_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_4_out = DecoderWeights_4_copy_0_fu_298;
    end else begin
        DecoderWeights_4_out = DecoderWeights_4_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_4_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_5_out = DecoderWeights_5_copy_0_fu_302;
    end else begin
        DecoderWeights_5_out = DecoderWeights_5_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_5_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_6_out = DecoderWeights_6_copy_0_fu_306;
    end else begin
        DecoderWeights_6_out = DecoderWeights_6_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_6_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_7_out = DecoderWeights_7_copy_0_fu_310;
    end else begin
        DecoderWeights_7_out = DecoderWeights_7_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_7_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_8_out = DecoderWeights_8_copy_0_fu_314;
    end else begin
        DecoderWeights_8_out = DecoderWeights_8_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_8_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_9_out = DecoderWeights_9_copy_0_fu_318;
    end else begin
        DecoderWeights_9_out = DecoderWeights_9_out_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        DecoderWeights_9_out_ap_vld = 1'b1;
    end else begin
        DecoderWeights_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        PrevDecoderWeightChanges_ce0 = 1'b1;
    end else begin
        PrevDecoderWeightChanges_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd0))) begin
        PrevDecoderWeightChanges_we0 = 1'b1;
    end else begin
        PrevDecoderWeightChanges_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln328_fu_1355_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln331_fu_1389_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign PrevDecoderWeightChanges_address0 = zext_ln337_fu_1406_p1;

assign PrevDecoderWeightChanges_d0 = 1'd0;

assign add_ln328_fu_1361_p2 = (d_fu_278 + 3'd1);

assign add_ln331_fu_1395_p2 = (h_reg_976 + 4'd1);

assign add_ln334_fu_1401_p2 = (zext_ln331_reg_2236 + zext_ln331_1_fu_1385_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign empty_49_fu_1367_p1 = d_fu_278[1:0];

assign icmp_ln328_fu_1355_p2 = ((d_fu_278 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln331_fu_1389_p2 = ((h_reg_976 == 4'd10) ? 1'b1 : 1'b0);

assign tmp_5_fu_1371_p4 = {{{empty_49_fu_1367_p1}, {empty_49_fu_1367_p1}}, {1'd0}};

assign zext_ln331_1_fu_1385_p1 = h_reg_976;

assign zext_ln331_fu_1381_p1 = tmp_5_fu_1371_p4;

assign zext_ln337_fu_1406_p1 = add_ln334_fu_1401_p2;

always @ (posedge ap_clk) begin
    zext_ln331_reg_2236[0] <= 1'b0;
    zext_ln331_reg_2236[5] <= 1'b0;
end

endmodule //Autoencoder_BackPropagateDecoderWeights
