// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Autoencoder_BackPropagate (
        p_read,
        EncoderWeights_0_out,
        p_read1,
        EncoderWeights_1_out,
        p_read2,
        EncoderWeights_2_out,
        p_read3,
        EncoderWeights_3_out,
        p_read4,
        EncoderWeights_4_out,
        p_read5,
        EncoderWeights_5_out,
        p_read6,
        EncoderWeights_6_out,
        p_read7,
        EncoderWeights_7_out,
        p_read8,
        EncoderWeights_8_out,
        p_read9,
        EncoderWeights_9_out,
        p_read10,
        EncoderWeights_10_out,
        p_read11,
        EncoderWeights_11_out,
        p_read12,
        EncoderWeights_12_out,
        p_read13,
        EncoderWeights_13_out,
        p_read14,
        EncoderWeights_14_out,
        p_read15,
        EncoderWeights_15_out,
        p_read16,
        EncoderWeights_16_out,
        p_read17,
        EncoderWeights_17_out,
        p_read18,
        EncoderWeights_18_out,
        p_read19,
        EncoderWeights_19_out,
        p_read20,
        EncoderWeights_20_out,
        p_read21,
        EncoderWeights_21_out,
        p_read22,
        EncoderWeights_22_out,
        p_read23,
        EncoderWeights_23_out,
        p_read24,
        EncoderWeights_24_out,
        p_read25,
        EncoderWeights_25_out,
        p_read26,
        EncoderWeights_26_out,
        p_read27,
        EncoderWeights_27_out,
        p_read28,
        EncoderWeights_28_out,
        p_read29,
        EncoderWeights_29_out,
        p_read30,
        EncoderWeights_30_out,
        p_read31,
        EncoderWeights_31_out,
        p_read32,
        EncoderWeights_32_out,
        p_read33,
        EncoderWeights_33_out,
        p_read34,
        EncoderWeights_34_out,
        p_read35,
        EncoderWeights_35_out,
        p_read36,
        EncoderWeights_36_out,
        p_read37,
        EncoderWeights_37_out,
        p_read38,
        EncoderWeights_38_out,
        p_read39,
        EncoderWeights_39_out,
        p_read40,
        DecoderWeights_0_out,
        p_read41,
        DecoderWeights_1_out,
        p_read42,
        DecoderWeights_2_out,
        p_read43,
        DecoderWeights_3_out,
        p_read44,
        DecoderWeights_4_out,
        p_read45,
        DecoderWeights_5_out,
        p_read46,
        DecoderWeights_6_out,
        p_read47,
        DecoderWeights_7_out,
        p_read48,
        DecoderWeights_8_out,
        p_read49,
        DecoderWeights_9_out,
        p_read50,
        DecoderWeights_10_out,
        p_read51,
        DecoderWeights_11_out,
        p_read52,
        DecoderWeights_12_out,
        p_read53,
        DecoderWeights_13_out,
        p_read54,
        DecoderWeights_14_out,
        p_read55,
        DecoderWeights_15_out,
        p_read56,
        DecoderWeights_16_out,
        p_read57,
        DecoderWeights_17_out,
        p_read58,
        DecoderWeights_18_out,
        p_read59,
        DecoderWeights_19_out,
        p_read60,
        DecoderWeights_20_out,
        p_read61,
        DecoderWeights_21_out,
        p_read62,
        DecoderWeights_22_out,
        p_read63,
        DecoderWeights_23_out,
        p_read64,
        DecoderWeights_24_out,
        p_read65,
        DecoderWeights_25_out,
        p_read66,
        DecoderWeights_26_out,
        p_read67,
        DecoderWeights_27_out,
        p_read68,
        DecoderWeights_28_out,
        p_read69,
        DecoderWeights_29_out,
        p_read70,
        DecoderWeights_30_out,
        p_read71,
        DecoderWeights_31_out,
        p_read72,
        DecoderWeights_32_out,
        p_read73,
        DecoderWeights_33_out,
        p_read74,
        DecoderWeights_34_out,
        p_read75,
        DecoderWeights_35_out,
        p_read76,
        DecoderWeights_36_out,
        p_read77,
        DecoderWeights_37_out,
        p_read78,
        DecoderWeights_38_out,
        p_read79,
        DecoderWeights_39_out,
        PrevEncoderWeightChanges_address0,
        PrevEncoderWeightChanges_ce0,
        PrevEncoderWeightChanges_d0,
        PrevEncoderWeightChanges_q0,
        PrevEncoderWeightChanges_we0,
        PrevEncoderWeightChanges_address1,
        PrevEncoderWeightChanges_ce1,
        PrevEncoderWeightChanges_d1,
        PrevEncoderWeightChanges_q1,
        PrevEncoderWeightChanges_we1,
        EncoderWeightChanges_address0,
        EncoderWeightChanges_ce0,
        EncoderWeightChanges_d0,
        EncoderWeightChanges_q0,
        EncoderWeightChanges_we0,
        EncoderWeightChanges_address1,
        EncoderWeightChanges_ce1,
        EncoderWeightChanges_d1,
        EncoderWeightChanges_q1,
        EncoderWeightChanges_we1,
        PrevDecoderWeightChanges_address0,
        PrevDecoderWeightChanges_ce0,
        PrevDecoderWeightChanges_d0,
        PrevDecoderWeightChanges_q0,
        PrevDecoderWeightChanges_we0,
        PrevDecoderWeightChanges_address1,
        PrevDecoderWeightChanges_ce1,
        PrevDecoderWeightChanges_d1,
        PrevDecoderWeightChanges_q1,
        PrevDecoderWeightChanges_we1,
        DecoderWeightChanges_address0,
        DecoderWeightChanges_ce0,
        DecoderWeightChanges_d0,
        DecoderWeightChanges_q0,
        DecoderWeightChanges_we0,
        DecoderWeightChanges_address1,
        DecoderWeightChanges_ce1,
        DecoderWeightChanges_d1,
        DecoderWeightChanges_q1,
        DecoderWeightChanges_we1,
        TotalErrorDeltas_address0,
        TotalErrorDeltas_ce0,
        TotalErrorDeltas_d0,
        TotalErrorDeltas_q0,
        TotalErrorDeltas_we0,
        TotalErrorDeltas_address1,
        TotalErrorDeltas_ce1,
        TotalErrorDeltas_d1,
        TotalErrorDeltas_q1,
        TotalErrorDeltas_we1,
        Deltas_address0,
        Deltas_ce0,
        Deltas_d0,
        Deltas_q0,
        Deltas_we0,
        Deltas_address1,
        Deltas_ce1,
        Deltas_d1,
        Deltas_q1,
        Deltas_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        p_read_ap_vld,
        EncoderWeights_0_out_ap_vld,
        p_read1_ap_vld,
        EncoderWeights_1_out_ap_vld,
        p_read2_ap_vld,
        EncoderWeights_2_out_ap_vld,
        p_read3_ap_vld,
        EncoderWeights_3_out_ap_vld,
        p_read4_ap_vld,
        EncoderWeights_4_out_ap_vld,
        p_read5_ap_vld,
        EncoderWeights_5_out_ap_vld,
        p_read6_ap_vld,
        EncoderWeights_6_out_ap_vld,
        p_read7_ap_vld,
        EncoderWeights_7_out_ap_vld,
        p_read8_ap_vld,
        EncoderWeights_8_out_ap_vld,
        p_read9_ap_vld,
        EncoderWeights_9_out_ap_vld,
        p_read10_ap_vld,
        EncoderWeights_10_out_ap_vld,
        p_read11_ap_vld,
        EncoderWeights_11_out_ap_vld,
        p_read12_ap_vld,
        EncoderWeights_12_out_ap_vld,
        p_read13_ap_vld,
        EncoderWeights_13_out_ap_vld,
        p_read14_ap_vld,
        EncoderWeights_14_out_ap_vld,
        p_read15_ap_vld,
        EncoderWeights_15_out_ap_vld,
        p_read16_ap_vld,
        EncoderWeights_16_out_ap_vld,
        p_read17_ap_vld,
        EncoderWeights_17_out_ap_vld,
        p_read18_ap_vld,
        EncoderWeights_18_out_ap_vld,
        p_read19_ap_vld,
        EncoderWeights_19_out_ap_vld,
        p_read20_ap_vld,
        EncoderWeights_20_out_ap_vld,
        p_read21_ap_vld,
        EncoderWeights_21_out_ap_vld,
        p_read22_ap_vld,
        EncoderWeights_22_out_ap_vld,
        p_read23_ap_vld,
        EncoderWeights_23_out_ap_vld,
        p_read24_ap_vld,
        EncoderWeights_24_out_ap_vld,
        p_read25_ap_vld,
        EncoderWeights_25_out_ap_vld,
        p_read26_ap_vld,
        EncoderWeights_26_out_ap_vld,
        p_read27_ap_vld,
        EncoderWeights_27_out_ap_vld,
        p_read28_ap_vld,
        EncoderWeights_28_out_ap_vld,
        p_read29_ap_vld,
        EncoderWeights_29_out_ap_vld,
        p_read30_ap_vld,
        EncoderWeights_30_out_ap_vld,
        p_read31_ap_vld,
        EncoderWeights_31_out_ap_vld,
        p_read32_ap_vld,
        EncoderWeights_32_out_ap_vld,
        p_read33_ap_vld,
        EncoderWeights_33_out_ap_vld,
        p_read34_ap_vld,
        EncoderWeights_34_out_ap_vld,
        p_read35_ap_vld,
        EncoderWeights_35_out_ap_vld,
        p_read36_ap_vld,
        EncoderWeights_36_out_ap_vld,
        p_read37_ap_vld,
        EncoderWeights_37_out_ap_vld,
        p_read38_ap_vld,
        EncoderWeights_38_out_ap_vld,
        p_read39_ap_vld,
        EncoderWeights_39_out_ap_vld,
        p_read40_ap_vld,
        DecoderWeights_0_out_ap_vld,
        p_read41_ap_vld,
        DecoderWeights_1_out_ap_vld,
        p_read42_ap_vld,
        DecoderWeights_2_out_ap_vld,
        p_read43_ap_vld,
        DecoderWeights_3_out_ap_vld,
        p_read44_ap_vld,
        DecoderWeights_4_out_ap_vld,
        p_read45_ap_vld,
        DecoderWeights_5_out_ap_vld,
        p_read46_ap_vld,
        DecoderWeights_6_out_ap_vld,
        p_read47_ap_vld,
        DecoderWeights_7_out_ap_vld,
        p_read48_ap_vld,
        DecoderWeights_8_out_ap_vld,
        p_read49_ap_vld,
        DecoderWeights_9_out_ap_vld,
        p_read50_ap_vld,
        DecoderWeights_10_out_ap_vld,
        p_read51_ap_vld,
        DecoderWeights_11_out_ap_vld,
        p_read52_ap_vld,
        DecoderWeights_12_out_ap_vld,
        p_read53_ap_vld,
        DecoderWeights_13_out_ap_vld,
        p_read54_ap_vld,
        DecoderWeights_14_out_ap_vld,
        p_read55_ap_vld,
        DecoderWeights_15_out_ap_vld,
        p_read56_ap_vld,
        DecoderWeights_16_out_ap_vld,
        p_read57_ap_vld,
        DecoderWeights_17_out_ap_vld,
        p_read58_ap_vld,
        DecoderWeights_18_out_ap_vld,
        p_read59_ap_vld,
        DecoderWeights_19_out_ap_vld,
        p_read60_ap_vld,
        DecoderWeights_20_out_ap_vld,
        p_read61_ap_vld,
        DecoderWeights_21_out_ap_vld,
        p_read62_ap_vld,
        DecoderWeights_22_out_ap_vld,
        p_read63_ap_vld,
        DecoderWeights_23_out_ap_vld,
        p_read64_ap_vld,
        DecoderWeights_24_out_ap_vld,
        p_read65_ap_vld,
        DecoderWeights_25_out_ap_vld,
        p_read66_ap_vld,
        DecoderWeights_26_out_ap_vld,
        p_read67_ap_vld,
        DecoderWeights_27_out_ap_vld,
        p_read68_ap_vld,
        DecoderWeights_28_out_ap_vld,
        p_read69_ap_vld,
        DecoderWeights_29_out_ap_vld,
        p_read70_ap_vld,
        DecoderWeights_30_out_ap_vld,
        p_read71_ap_vld,
        DecoderWeights_31_out_ap_vld,
        p_read72_ap_vld,
        DecoderWeights_32_out_ap_vld,
        p_read73_ap_vld,
        DecoderWeights_33_out_ap_vld,
        p_read74_ap_vld,
        DecoderWeights_34_out_ap_vld,
        p_read75_ap_vld,
        DecoderWeights_35_out_ap_vld,
        p_read76_ap_vld,
        DecoderWeights_36_out_ap_vld,
        p_read77_ap_vld,
        DecoderWeights_37_out_ap_vld,
        p_read78_ap_vld,
        DecoderWeights_38_out_ap_vld,
        p_read79_ap_vld,
        DecoderWeights_39_out_ap_vld,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [0:0] p_read;
output  [0:0] EncoderWeights_0_out;
input  [0:0] p_read1;
output  [0:0] EncoderWeights_1_out;
input  [0:0] p_read2;
output  [0:0] EncoderWeights_2_out;
input  [0:0] p_read3;
output  [0:0] EncoderWeights_3_out;
input  [0:0] p_read4;
output  [0:0] EncoderWeights_4_out;
input  [0:0] p_read5;
output  [0:0] EncoderWeights_5_out;
input  [0:0] p_read6;
output  [0:0] EncoderWeights_6_out;
input  [0:0] p_read7;
output  [0:0] EncoderWeights_7_out;
input  [0:0] p_read8;
output  [0:0] EncoderWeights_8_out;
input  [0:0] p_read9;
output  [0:0] EncoderWeights_9_out;
input  [0:0] p_read10;
output  [0:0] EncoderWeights_10_out;
input  [0:0] p_read11;
output  [0:0] EncoderWeights_11_out;
input  [0:0] p_read12;
output  [0:0] EncoderWeights_12_out;
input  [0:0] p_read13;
output  [0:0] EncoderWeights_13_out;
input  [0:0] p_read14;
output  [0:0] EncoderWeights_14_out;
input  [0:0] p_read15;
output  [0:0] EncoderWeights_15_out;
input  [0:0] p_read16;
output  [0:0] EncoderWeights_16_out;
input  [0:0] p_read17;
output  [0:0] EncoderWeights_17_out;
input  [0:0] p_read18;
output  [0:0] EncoderWeights_18_out;
input  [0:0] p_read19;
output  [0:0] EncoderWeights_19_out;
input  [0:0] p_read20;
output  [0:0] EncoderWeights_20_out;
input  [0:0] p_read21;
output  [0:0] EncoderWeights_21_out;
input  [0:0] p_read22;
output  [0:0] EncoderWeights_22_out;
input  [0:0] p_read23;
output  [0:0] EncoderWeights_23_out;
input  [0:0] p_read24;
output  [0:0] EncoderWeights_24_out;
input  [0:0] p_read25;
output  [0:0] EncoderWeights_25_out;
input  [0:0] p_read26;
output  [0:0] EncoderWeights_26_out;
input  [0:0] p_read27;
output  [0:0] EncoderWeights_27_out;
input  [0:0] p_read28;
output  [0:0] EncoderWeights_28_out;
input  [0:0] p_read29;
output  [0:0] EncoderWeights_29_out;
input  [0:0] p_read30;
output  [0:0] EncoderWeights_30_out;
input  [0:0] p_read31;
output  [0:0] EncoderWeights_31_out;
input  [0:0] p_read32;
output  [0:0] EncoderWeights_32_out;
input  [0:0] p_read33;
output  [0:0] EncoderWeights_33_out;
input  [0:0] p_read34;
output  [0:0] EncoderWeights_34_out;
input  [0:0] p_read35;
output  [0:0] EncoderWeights_35_out;
input  [0:0] p_read36;
output  [0:0] EncoderWeights_36_out;
input  [0:0] p_read37;
output  [0:0] EncoderWeights_37_out;
input  [0:0] p_read38;
output  [0:0] EncoderWeights_38_out;
input  [0:0] p_read39;
output  [0:0] EncoderWeights_39_out;
input  [0:0] p_read40;
output  [0:0] DecoderWeights_0_out;
input  [0:0] p_read41;
output  [0:0] DecoderWeights_1_out;
input  [0:0] p_read42;
output  [0:0] DecoderWeights_2_out;
input  [0:0] p_read43;
output  [0:0] DecoderWeights_3_out;
input  [0:0] p_read44;
output  [0:0] DecoderWeights_4_out;
input  [0:0] p_read45;
output  [0:0] DecoderWeights_5_out;
input  [0:0] p_read46;
output  [0:0] DecoderWeights_6_out;
input  [0:0] p_read47;
output  [0:0] DecoderWeights_7_out;
input  [0:0] p_read48;
output  [0:0] DecoderWeights_8_out;
input  [0:0] p_read49;
output  [0:0] DecoderWeights_9_out;
input  [0:0] p_read50;
output  [0:0] DecoderWeights_10_out;
input  [0:0] p_read51;
output  [0:0] DecoderWeights_11_out;
input  [0:0] p_read52;
output  [0:0] DecoderWeights_12_out;
input  [0:0] p_read53;
output  [0:0] DecoderWeights_13_out;
input  [0:0] p_read54;
output  [0:0] DecoderWeights_14_out;
input  [0:0] p_read55;
output  [0:0] DecoderWeights_15_out;
input  [0:0] p_read56;
output  [0:0] DecoderWeights_16_out;
input  [0:0] p_read57;
output  [0:0] DecoderWeights_17_out;
input  [0:0] p_read58;
output  [0:0] DecoderWeights_18_out;
input  [0:0] p_read59;
output  [0:0] DecoderWeights_19_out;
input  [0:0] p_read60;
output  [0:0] DecoderWeights_20_out;
input  [0:0] p_read61;
output  [0:0] DecoderWeights_21_out;
input  [0:0] p_read62;
output  [0:0] DecoderWeights_22_out;
input  [0:0] p_read63;
output  [0:0] DecoderWeights_23_out;
input  [0:0] p_read64;
output  [0:0] DecoderWeights_24_out;
input  [0:0] p_read65;
output  [0:0] DecoderWeights_25_out;
input  [0:0] p_read66;
output  [0:0] DecoderWeights_26_out;
input  [0:0] p_read67;
output  [0:0] DecoderWeights_27_out;
input  [0:0] p_read68;
output  [0:0] DecoderWeights_28_out;
input  [0:0] p_read69;
output  [0:0] DecoderWeights_29_out;
input  [0:0] p_read70;
output  [0:0] DecoderWeights_30_out;
input  [0:0] p_read71;
output  [0:0] DecoderWeights_31_out;
input  [0:0] p_read72;
output  [0:0] DecoderWeights_32_out;
input  [0:0] p_read73;
output  [0:0] DecoderWeights_33_out;
input  [0:0] p_read74;
output  [0:0] DecoderWeights_34_out;
input  [0:0] p_read75;
output  [0:0] DecoderWeights_35_out;
input  [0:0] p_read76;
output  [0:0] DecoderWeights_36_out;
input  [0:0] p_read77;
output  [0:0] DecoderWeights_37_out;
input  [0:0] p_read78;
output  [0:0] DecoderWeights_38_out;
input  [0:0] p_read79;
output  [0:0] DecoderWeights_39_out;
output  [5:0] PrevEncoderWeightChanges_address0;
output   PrevEncoderWeightChanges_ce0;
output  [0:0] PrevEncoderWeightChanges_d0;
input  [0:0] PrevEncoderWeightChanges_q0;
output   PrevEncoderWeightChanges_we0;
output  [5:0] PrevEncoderWeightChanges_address1;
output   PrevEncoderWeightChanges_ce1;
output  [0:0] PrevEncoderWeightChanges_d1;
input  [0:0] PrevEncoderWeightChanges_q1;
output   PrevEncoderWeightChanges_we1;
output  [5:0] EncoderWeightChanges_address0;
output   EncoderWeightChanges_ce0;
output  [0:0] EncoderWeightChanges_d0;
input  [0:0] EncoderWeightChanges_q0;
output   EncoderWeightChanges_we0;
output  [5:0] EncoderWeightChanges_address1;
output   EncoderWeightChanges_ce1;
output  [0:0] EncoderWeightChanges_d1;
input  [0:0] EncoderWeightChanges_q1;
output   EncoderWeightChanges_we1;
output  [5:0] PrevDecoderWeightChanges_address0;
output   PrevDecoderWeightChanges_ce0;
output  [0:0] PrevDecoderWeightChanges_d0;
input  [0:0] PrevDecoderWeightChanges_q0;
output   PrevDecoderWeightChanges_we0;
output  [5:0] PrevDecoderWeightChanges_address1;
output   PrevDecoderWeightChanges_ce1;
output  [0:0] PrevDecoderWeightChanges_d1;
input  [0:0] PrevDecoderWeightChanges_q1;
output   PrevDecoderWeightChanges_we1;
output  [5:0] DecoderWeightChanges_address0;
output   DecoderWeightChanges_ce0;
output  [0:0] DecoderWeightChanges_d0;
input  [0:0] DecoderWeightChanges_q0;
output   DecoderWeightChanges_we0;
output  [5:0] DecoderWeightChanges_address1;
output   DecoderWeightChanges_ce1;
output  [0:0] DecoderWeightChanges_d1;
input  [0:0] DecoderWeightChanges_q1;
output   DecoderWeightChanges_we1;
output  [5:0] TotalErrorDeltas_address0;
output   TotalErrorDeltas_ce0;
output  [0:0] TotalErrorDeltas_d0;
input  [0:0] TotalErrorDeltas_q0;
output   TotalErrorDeltas_we0;
output  [5:0] TotalErrorDeltas_address1;
output   TotalErrorDeltas_ce1;
output  [0:0] TotalErrorDeltas_d1;
input  [0:0] TotalErrorDeltas_q1;
output   TotalErrorDeltas_we1;
output  [1:0] Deltas_address0;
output   Deltas_ce0;
output  [0:0] Deltas_d0;
input  [0:0] Deltas_q0;
output   Deltas_we0;
output  [1:0] Deltas_address1;
output   Deltas_ce1;
output  [0:0] Deltas_d1;
input  [0:0] Deltas_q1;
output   Deltas_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   p_read_ap_vld;
output   EncoderWeights_0_out_ap_vld;
input   p_read1_ap_vld;
output   EncoderWeights_1_out_ap_vld;
input   p_read2_ap_vld;
output   EncoderWeights_2_out_ap_vld;
input   p_read3_ap_vld;
output   EncoderWeights_3_out_ap_vld;
input   p_read4_ap_vld;
output   EncoderWeights_4_out_ap_vld;
input   p_read5_ap_vld;
output   EncoderWeights_5_out_ap_vld;
input   p_read6_ap_vld;
output   EncoderWeights_6_out_ap_vld;
input   p_read7_ap_vld;
output   EncoderWeights_7_out_ap_vld;
input   p_read8_ap_vld;
output   EncoderWeights_8_out_ap_vld;
input   p_read9_ap_vld;
output   EncoderWeights_9_out_ap_vld;
input   p_read10_ap_vld;
output   EncoderWeights_10_out_ap_vld;
input   p_read11_ap_vld;
output   EncoderWeights_11_out_ap_vld;
input   p_read12_ap_vld;
output   EncoderWeights_12_out_ap_vld;
input   p_read13_ap_vld;
output   EncoderWeights_13_out_ap_vld;
input   p_read14_ap_vld;
output   EncoderWeights_14_out_ap_vld;
input   p_read15_ap_vld;
output   EncoderWeights_15_out_ap_vld;
input   p_read16_ap_vld;
output   EncoderWeights_16_out_ap_vld;
input   p_read17_ap_vld;
output   EncoderWeights_17_out_ap_vld;
input   p_read18_ap_vld;
output   EncoderWeights_18_out_ap_vld;
input   p_read19_ap_vld;
output   EncoderWeights_19_out_ap_vld;
input   p_read20_ap_vld;
output   EncoderWeights_20_out_ap_vld;
input   p_read21_ap_vld;
output   EncoderWeights_21_out_ap_vld;
input   p_read22_ap_vld;
output   EncoderWeights_22_out_ap_vld;
input   p_read23_ap_vld;
output   EncoderWeights_23_out_ap_vld;
input   p_read24_ap_vld;
output   EncoderWeights_24_out_ap_vld;
input   p_read25_ap_vld;
output   EncoderWeights_25_out_ap_vld;
input   p_read26_ap_vld;
output   EncoderWeights_26_out_ap_vld;
input   p_read27_ap_vld;
output   EncoderWeights_27_out_ap_vld;
input   p_read28_ap_vld;
output   EncoderWeights_28_out_ap_vld;
input   p_read29_ap_vld;
output   EncoderWeights_29_out_ap_vld;
input   p_read30_ap_vld;
output   EncoderWeights_30_out_ap_vld;
input   p_read31_ap_vld;
output   EncoderWeights_31_out_ap_vld;
input   p_read32_ap_vld;
output   EncoderWeights_32_out_ap_vld;
input   p_read33_ap_vld;
output   EncoderWeights_33_out_ap_vld;
input   p_read34_ap_vld;
output   EncoderWeights_34_out_ap_vld;
input   p_read35_ap_vld;
output   EncoderWeights_35_out_ap_vld;
input   p_read36_ap_vld;
output   EncoderWeights_36_out_ap_vld;
input   p_read37_ap_vld;
output   EncoderWeights_37_out_ap_vld;
input   p_read38_ap_vld;
output   EncoderWeights_38_out_ap_vld;
input   p_read39_ap_vld;
output   EncoderWeights_39_out_ap_vld;
input   p_read40_ap_vld;
output   DecoderWeights_0_out_ap_vld;
input   p_read41_ap_vld;
output   DecoderWeights_1_out_ap_vld;
input   p_read42_ap_vld;
output   DecoderWeights_2_out_ap_vld;
input   p_read43_ap_vld;
output   DecoderWeights_3_out_ap_vld;
input   p_read44_ap_vld;
output   DecoderWeights_4_out_ap_vld;
input   p_read45_ap_vld;
output   DecoderWeights_5_out_ap_vld;
input   p_read46_ap_vld;
output   DecoderWeights_6_out_ap_vld;
input   p_read47_ap_vld;
output   DecoderWeights_7_out_ap_vld;
input   p_read48_ap_vld;
output   DecoderWeights_8_out_ap_vld;
input   p_read49_ap_vld;
output   DecoderWeights_9_out_ap_vld;
input   p_read50_ap_vld;
output   DecoderWeights_10_out_ap_vld;
input   p_read51_ap_vld;
output   DecoderWeights_11_out_ap_vld;
input   p_read52_ap_vld;
output   DecoderWeights_12_out_ap_vld;
input   p_read53_ap_vld;
output   DecoderWeights_13_out_ap_vld;
input   p_read54_ap_vld;
output   DecoderWeights_14_out_ap_vld;
input   p_read55_ap_vld;
output   DecoderWeights_15_out_ap_vld;
input   p_read56_ap_vld;
output   DecoderWeights_16_out_ap_vld;
input   p_read57_ap_vld;
output   DecoderWeights_17_out_ap_vld;
input   p_read58_ap_vld;
output   DecoderWeights_18_out_ap_vld;
input   p_read59_ap_vld;
output   DecoderWeights_19_out_ap_vld;
input   p_read60_ap_vld;
output   DecoderWeights_20_out_ap_vld;
input   p_read61_ap_vld;
output   DecoderWeights_21_out_ap_vld;
input   p_read62_ap_vld;
output   DecoderWeights_22_out_ap_vld;
input   p_read63_ap_vld;
output   DecoderWeights_23_out_ap_vld;
input   p_read64_ap_vld;
output   DecoderWeights_24_out_ap_vld;
input   p_read65_ap_vld;
output   DecoderWeights_25_out_ap_vld;
input   p_read66_ap_vld;
output   DecoderWeights_26_out_ap_vld;
input   p_read67_ap_vld;
output   DecoderWeights_27_out_ap_vld;
input   p_read68_ap_vld;
output   DecoderWeights_28_out_ap_vld;
input   p_read69_ap_vld;
output   DecoderWeights_29_out_ap_vld;
input   p_read70_ap_vld;
output   DecoderWeights_30_out_ap_vld;
input   p_read71_ap_vld;
output   DecoderWeights_31_out_ap_vld;
input   p_read72_ap_vld;
output   DecoderWeights_32_out_ap_vld;
input   p_read73_ap_vld;
output   DecoderWeights_33_out_ap_vld;
input   p_read74_ap_vld;
output   DecoderWeights_34_out_ap_vld;
input   p_read75_ap_vld;
output   DecoderWeights_35_out_ap_vld;
input   p_read76_ap_vld;
output   DecoderWeights_36_out_ap_vld;
input   p_read77_ap_vld;
output   DecoderWeights_37_out_ap_vld;
input   p_read78_ap_vld;
output   DecoderWeights_38_out_ap_vld;
input   p_read79_ap_vld;
output   DecoderWeights_39_out_ap_vld;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    BackPropagateDecoderWeightChanges_U0_ap_start;
wire    BackPropagateDecoderWeightChanges_U0_ap_done;
wire    BackPropagateDecoderWeightChanges_U0_ap_continue;
wire    BackPropagateDecoderWeightChanges_U0_ap_idle;
wire    BackPropagateDecoderWeightChanges_U0_ap_ready;
wire   [5:0] BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_address0;
wire    BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_ce0;
wire    BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_we0;
wire   [0:0] BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_d0;
wire   [1:0] BackPropagateDecoderWeightChanges_U0_Deltas_address0;
wire    BackPropagateDecoderWeightChanges_U0_Deltas_ce0;
wire    BackPropagateDecoderWeightChanges_U0_Deltas_we0;
wire   [0:0] BackPropagateDecoderWeightChanges_U0_Deltas_d0;
wire    ap_sync_continue;
wire    BackPropagateEncoderWeightsChanges_U0_ap_start;
wire    BackPropagateEncoderWeightsChanges_U0_ap_done;
wire    BackPropagateEncoderWeightsChanges_U0_ap_continue;
wire    BackPropagateEncoderWeightsChanges_U0_ap_idle;
wire    BackPropagateEncoderWeightsChanges_U0_ap_ready;
wire   [5:0] BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_address0;
wire    BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_ce0;
wire    BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_we0;
wire   [0:0] BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_d0;
wire   [5:0] BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_address0;
wire    BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_ce0;
wire    BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_we0;
wire   [0:0] BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_d0;
wire    BackPropagateEncoderWeights_U0_ap_start;
wire    BackPropagateEncoderWeights_U0_ap_done;
wire    BackPropagateEncoderWeights_U0_ap_continue;
wire    BackPropagateEncoderWeights_U0_ap_idle;
wire    BackPropagateEncoderWeights_U0_ap_ready;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_0_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_0_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_1_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_1_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_2_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_2_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_3_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_3_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_4_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_4_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_5_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_5_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_6_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_6_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_7_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_7_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_8_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_8_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_9_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_9_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_10_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_10_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_11_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_11_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_12_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_12_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_13_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_13_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_14_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_14_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_15_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_15_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_16_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_16_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_17_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_17_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_18_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_18_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_19_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_19_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_20_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_20_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_21_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_21_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_22_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_22_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_23_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_23_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_24_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_24_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_25_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_25_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_26_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_26_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_27_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_27_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_28_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_28_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_29_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_29_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_30_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_30_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_31_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_31_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_32_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_32_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_33_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_33_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_34_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_34_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_35_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_35_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_36_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_36_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_37_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_37_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_38_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_38_out_ap_vld;
wire   [0:0] BackPropagateEncoderWeights_U0_EncoderWeights_39_out;
wire    BackPropagateEncoderWeights_U0_EncoderWeights_39_out_ap_vld;
wire   [5:0] BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_address0;
wire    BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_ce0;
wire    BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_we0;
wire   [0:0] BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_d0;
wire    BackPropagateDecoderWeights_U0_ap_start;
wire    BackPropagateDecoderWeights_U0_ap_done;
wire    BackPropagateDecoderWeights_U0_ap_continue;
wire    BackPropagateDecoderWeights_U0_ap_idle;
wire    BackPropagateDecoderWeights_U0_ap_ready;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_0_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_0_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_1_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_1_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_2_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_2_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_3_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_3_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_4_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_4_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_5_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_5_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_6_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_6_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_7_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_7_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_8_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_8_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_9_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_9_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_10_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_10_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_11_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_11_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_12_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_12_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_13_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_13_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_14_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_14_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_15_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_15_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_16_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_16_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_17_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_17_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_18_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_18_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_19_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_19_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_20_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_20_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_21_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_21_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_22_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_22_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_23_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_23_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_24_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_24_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_25_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_25_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_26_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_26_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_27_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_27_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_28_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_28_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_29_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_29_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_30_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_30_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_31_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_31_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_32_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_32_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_33_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_33_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_34_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_34_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_35_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_35_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_36_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_36_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_37_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_37_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_38_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_38_out_ap_vld;
wire   [0:0] BackPropagateDecoderWeights_U0_DecoderWeights_39_out;
wire    BackPropagateDecoderWeights_U0_DecoderWeights_39_out_ap_vld;
wire   [5:0] BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_address0;
wire    BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_ce0;
wire    BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_we0;
wire   [0:0] BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_d0;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_BackPropagateDecoderWeightChanges_U0_ap_ready;
wire    ap_sync_BackPropagateDecoderWeightChanges_U0_ap_ready;
reg    ap_sync_reg_BackPropagateEncoderWeightsChanges_U0_ap_ready;
wire    ap_sync_BackPropagateEncoderWeightsChanges_U0_ap_ready;
reg    ap_sync_reg_BackPropagateEncoderWeights_U0_ap_ready;
wire    ap_sync_BackPropagateEncoderWeights_U0_ap_ready;
reg    ap_sync_reg_BackPropagateDecoderWeights_U0_ap_ready;
wire    ap_sync_BackPropagateDecoderWeights_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_BackPropagateDecoderWeightChanges_U0_ap_ready = 1'b0;
#0 ap_sync_reg_BackPropagateEncoderWeightsChanges_U0_ap_ready = 1'b0;
#0 ap_sync_reg_BackPropagateEncoderWeights_U0_ap_ready = 1'b0;
#0 ap_sync_reg_BackPropagateDecoderWeights_U0_ap_ready = 1'b0;
end

Autoencoder_BackPropagateDecoderWeightChanges BackPropagateDecoderWeightChanges_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(BackPropagateDecoderWeightChanges_U0_ap_start),
    .ap_done(BackPropagateDecoderWeightChanges_U0_ap_done),
    .ap_continue(BackPropagateDecoderWeightChanges_U0_ap_continue),
    .ap_idle(BackPropagateDecoderWeightChanges_U0_ap_idle),
    .ap_ready(BackPropagateDecoderWeightChanges_U0_ap_ready),
    .DecoderWeightChanges_address0(BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_address0),
    .DecoderWeightChanges_ce0(BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_ce0),
    .DecoderWeightChanges_we0(BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_we0),
    .DecoderWeightChanges_d0(BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_d0),
    .Deltas_address0(BackPropagateDecoderWeightChanges_U0_Deltas_address0),
    .Deltas_ce0(BackPropagateDecoderWeightChanges_U0_Deltas_ce0),
    .Deltas_we0(BackPropagateDecoderWeightChanges_U0_Deltas_we0),
    .Deltas_d0(BackPropagateDecoderWeightChanges_U0_Deltas_d0)
);

Autoencoder_BackPropagateEncoderWeightsChanges BackPropagateEncoderWeightsChanges_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(BackPropagateEncoderWeightsChanges_U0_ap_start),
    .ap_done(BackPropagateEncoderWeightsChanges_U0_ap_done),
    .ap_continue(BackPropagateEncoderWeightsChanges_U0_ap_continue),
    .ap_idle(BackPropagateEncoderWeightsChanges_U0_ap_idle),
    .ap_ready(BackPropagateEncoderWeightsChanges_U0_ap_ready),
    .EncoderWeightChanges_address0(BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_address0),
    .EncoderWeightChanges_ce0(BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_ce0),
    .EncoderWeightChanges_we0(BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_we0),
    .EncoderWeightChanges_d0(BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_d0),
    .TotalErrorDeltas_address0(BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_address0),
    .TotalErrorDeltas_ce0(BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_ce0),
    .TotalErrorDeltas_we0(BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_we0),
    .TotalErrorDeltas_d0(BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_d0)
);

Autoencoder_BackPropagateEncoderWeights BackPropagateEncoderWeights_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(BackPropagateEncoderWeights_U0_ap_start),
    .ap_done(BackPropagateEncoderWeights_U0_ap_done),
    .ap_continue(BackPropagateEncoderWeights_U0_ap_continue),
    .ap_idle(BackPropagateEncoderWeights_U0_ap_idle),
    .ap_ready(BackPropagateEncoderWeights_U0_ap_ready),
    .p_read(p_read),
    .EncoderWeights_0_out(BackPropagateEncoderWeights_U0_EncoderWeights_0_out),
    .EncoderWeights_0_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_0_out_ap_vld),
    .p_read1(p_read1),
    .EncoderWeights_1_out(BackPropagateEncoderWeights_U0_EncoderWeights_1_out),
    .EncoderWeights_1_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_1_out_ap_vld),
    .p_read2(p_read2),
    .EncoderWeights_2_out(BackPropagateEncoderWeights_U0_EncoderWeights_2_out),
    .EncoderWeights_2_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_2_out_ap_vld),
    .p_read3(p_read3),
    .EncoderWeights_3_out(BackPropagateEncoderWeights_U0_EncoderWeights_3_out),
    .EncoderWeights_3_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_3_out_ap_vld),
    .p_read4(p_read4),
    .EncoderWeights_4_out(BackPropagateEncoderWeights_U0_EncoderWeights_4_out),
    .EncoderWeights_4_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_4_out_ap_vld),
    .p_read5(p_read5),
    .EncoderWeights_5_out(BackPropagateEncoderWeights_U0_EncoderWeights_5_out),
    .EncoderWeights_5_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_5_out_ap_vld),
    .p_read6(p_read6),
    .EncoderWeights_6_out(BackPropagateEncoderWeights_U0_EncoderWeights_6_out),
    .EncoderWeights_6_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_6_out_ap_vld),
    .p_read7(p_read7),
    .EncoderWeights_7_out(BackPropagateEncoderWeights_U0_EncoderWeights_7_out),
    .EncoderWeights_7_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_7_out_ap_vld),
    .p_read8(p_read8),
    .EncoderWeights_8_out(BackPropagateEncoderWeights_U0_EncoderWeights_8_out),
    .EncoderWeights_8_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_8_out_ap_vld),
    .p_read9(p_read9),
    .EncoderWeights_9_out(BackPropagateEncoderWeights_U0_EncoderWeights_9_out),
    .EncoderWeights_9_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_9_out_ap_vld),
    .p_read10(p_read10),
    .EncoderWeights_10_out(BackPropagateEncoderWeights_U0_EncoderWeights_10_out),
    .EncoderWeights_10_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_10_out_ap_vld),
    .p_read11(p_read11),
    .EncoderWeights_11_out(BackPropagateEncoderWeights_U0_EncoderWeights_11_out),
    .EncoderWeights_11_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_11_out_ap_vld),
    .p_read12(p_read12),
    .EncoderWeights_12_out(BackPropagateEncoderWeights_U0_EncoderWeights_12_out),
    .EncoderWeights_12_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_12_out_ap_vld),
    .p_read13(p_read13),
    .EncoderWeights_13_out(BackPropagateEncoderWeights_U0_EncoderWeights_13_out),
    .EncoderWeights_13_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_13_out_ap_vld),
    .p_read14(p_read14),
    .EncoderWeights_14_out(BackPropagateEncoderWeights_U0_EncoderWeights_14_out),
    .EncoderWeights_14_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_14_out_ap_vld),
    .p_read15(p_read15),
    .EncoderWeights_15_out(BackPropagateEncoderWeights_U0_EncoderWeights_15_out),
    .EncoderWeights_15_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_15_out_ap_vld),
    .p_read16(p_read16),
    .EncoderWeights_16_out(BackPropagateEncoderWeights_U0_EncoderWeights_16_out),
    .EncoderWeights_16_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_16_out_ap_vld),
    .p_read17(p_read17),
    .EncoderWeights_17_out(BackPropagateEncoderWeights_U0_EncoderWeights_17_out),
    .EncoderWeights_17_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_17_out_ap_vld),
    .p_read18(p_read18),
    .EncoderWeights_18_out(BackPropagateEncoderWeights_U0_EncoderWeights_18_out),
    .EncoderWeights_18_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_18_out_ap_vld),
    .p_read19(p_read19),
    .EncoderWeights_19_out(BackPropagateEncoderWeights_U0_EncoderWeights_19_out),
    .EncoderWeights_19_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_19_out_ap_vld),
    .p_read20(p_read20),
    .EncoderWeights_20_out(BackPropagateEncoderWeights_U0_EncoderWeights_20_out),
    .EncoderWeights_20_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_20_out_ap_vld),
    .p_read21(p_read21),
    .EncoderWeights_21_out(BackPropagateEncoderWeights_U0_EncoderWeights_21_out),
    .EncoderWeights_21_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_21_out_ap_vld),
    .p_read22(p_read22),
    .EncoderWeights_22_out(BackPropagateEncoderWeights_U0_EncoderWeights_22_out),
    .EncoderWeights_22_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_22_out_ap_vld),
    .p_read23(p_read23),
    .EncoderWeights_23_out(BackPropagateEncoderWeights_U0_EncoderWeights_23_out),
    .EncoderWeights_23_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_23_out_ap_vld),
    .p_read24(p_read24),
    .EncoderWeights_24_out(BackPropagateEncoderWeights_U0_EncoderWeights_24_out),
    .EncoderWeights_24_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_24_out_ap_vld),
    .p_read25(p_read25),
    .EncoderWeights_25_out(BackPropagateEncoderWeights_U0_EncoderWeights_25_out),
    .EncoderWeights_25_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_25_out_ap_vld),
    .p_read26(p_read26),
    .EncoderWeights_26_out(BackPropagateEncoderWeights_U0_EncoderWeights_26_out),
    .EncoderWeights_26_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_26_out_ap_vld),
    .p_read27(p_read27),
    .EncoderWeights_27_out(BackPropagateEncoderWeights_U0_EncoderWeights_27_out),
    .EncoderWeights_27_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_27_out_ap_vld),
    .p_read28(p_read28),
    .EncoderWeights_28_out(BackPropagateEncoderWeights_U0_EncoderWeights_28_out),
    .EncoderWeights_28_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_28_out_ap_vld),
    .p_read29(p_read29),
    .EncoderWeights_29_out(BackPropagateEncoderWeights_U0_EncoderWeights_29_out),
    .EncoderWeights_29_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_29_out_ap_vld),
    .p_read30(p_read30),
    .EncoderWeights_30_out(BackPropagateEncoderWeights_U0_EncoderWeights_30_out),
    .EncoderWeights_30_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_30_out_ap_vld),
    .p_read31(p_read31),
    .EncoderWeights_31_out(BackPropagateEncoderWeights_U0_EncoderWeights_31_out),
    .EncoderWeights_31_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_31_out_ap_vld),
    .p_read32(p_read32),
    .EncoderWeights_32_out(BackPropagateEncoderWeights_U0_EncoderWeights_32_out),
    .EncoderWeights_32_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_32_out_ap_vld),
    .p_read33(p_read33),
    .EncoderWeights_33_out(BackPropagateEncoderWeights_U0_EncoderWeights_33_out),
    .EncoderWeights_33_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_33_out_ap_vld),
    .p_read34(p_read34),
    .EncoderWeights_34_out(BackPropagateEncoderWeights_U0_EncoderWeights_34_out),
    .EncoderWeights_34_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_34_out_ap_vld),
    .p_read35(p_read35),
    .EncoderWeights_35_out(BackPropagateEncoderWeights_U0_EncoderWeights_35_out),
    .EncoderWeights_35_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_35_out_ap_vld),
    .p_read36(p_read36),
    .EncoderWeights_36_out(BackPropagateEncoderWeights_U0_EncoderWeights_36_out),
    .EncoderWeights_36_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_36_out_ap_vld),
    .p_read37(p_read37),
    .EncoderWeights_37_out(BackPropagateEncoderWeights_U0_EncoderWeights_37_out),
    .EncoderWeights_37_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_37_out_ap_vld),
    .p_read38(p_read38),
    .EncoderWeights_38_out(BackPropagateEncoderWeights_U0_EncoderWeights_38_out),
    .EncoderWeights_38_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_38_out_ap_vld),
    .p_read39(p_read39),
    .EncoderWeights_39_out(BackPropagateEncoderWeights_U0_EncoderWeights_39_out),
    .EncoderWeights_39_out_ap_vld(BackPropagateEncoderWeights_U0_EncoderWeights_39_out_ap_vld),
    .PrevEncoderWeightChanges_address0(BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_address0),
    .PrevEncoderWeightChanges_ce0(BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_ce0),
    .PrevEncoderWeightChanges_we0(BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_we0),
    .PrevEncoderWeightChanges_d0(BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_d0)
);

Autoencoder_BackPropagateDecoderWeights BackPropagateDecoderWeights_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(BackPropagateDecoderWeights_U0_ap_start),
    .ap_done(BackPropagateDecoderWeights_U0_ap_done),
    .ap_continue(BackPropagateDecoderWeights_U0_ap_continue),
    .ap_idle(BackPropagateDecoderWeights_U0_ap_idle),
    .ap_ready(BackPropagateDecoderWeights_U0_ap_ready),
    .p_read(p_read40),
    .DecoderWeights_0_out(BackPropagateDecoderWeights_U0_DecoderWeights_0_out),
    .DecoderWeights_0_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_0_out_ap_vld),
    .p_read1(p_read41),
    .DecoderWeights_1_out(BackPropagateDecoderWeights_U0_DecoderWeights_1_out),
    .DecoderWeights_1_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_1_out_ap_vld),
    .p_read2(p_read42),
    .DecoderWeights_2_out(BackPropagateDecoderWeights_U0_DecoderWeights_2_out),
    .DecoderWeights_2_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_2_out_ap_vld),
    .p_read3(p_read43),
    .DecoderWeights_3_out(BackPropagateDecoderWeights_U0_DecoderWeights_3_out),
    .DecoderWeights_3_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_3_out_ap_vld),
    .p_read4(p_read44),
    .DecoderWeights_4_out(BackPropagateDecoderWeights_U0_DecoderWeights_4_out),
    .DecoderWeights_4_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_4_out_ap_vld),
    .p_read5(p_read45),
    .DecoderWeights_5_out(BackPropagateDecoderWeights_U0_DecoderWeights_5_out),
    .DecoderWeights_5_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_5_out_ap_vld),
    .p_read6(p_read46),
    .DecoderWeights_6_out(BackPropagateDecoderWeights_U0_DecoderWeights_6_out),
    .DecoderWeights_6_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_6_out_ap_vld),
    .p_read7(p_read47),
    .DecoderWeights_7_out(BackPropagateDecoderWeights_U0_DecoderWeights_7_out),
    .DecoderWeights_7_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_7_out_ap_vld),
    .p_read8(p_read48),
    .DecoderWeights_8_out(BackPropagateDecoderWeights_U0_DecoderWeights_8_out),
    .DecoderWeights_8_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_8_out_ap_vld),
    .p_read9(p_read49),
    .DecoderWeights_9_out(BackPropagateDecoderWeights_U0_DecoderWeights_9_out),
    .DecoderWeights_9_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_9_out_ap_vld),
    .p_read10(p_read50),
    .DecoderWeights_10_out(BackPropagateDecoderWeights_U0_DecoderWeights_10_out),
    .DecoderWeights_10_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_10_out_ap_vld),
    .p_read11(p_read51),
    .DecoderWeights_11_out(BackPropagateDecoderWeights_U0_DecoderWeights_11_out),
    .DecoderWeights_11_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_11_out_ap_vld),
    .p_read12(p_read52),
    .DecoderWeights_12_out(BackPropagateDecoderWeights_U0_DecoderWeights_12_out),
    .DecoderWeights_12_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_12_out_ap_vld),
    .p_read13(p_read53),
    .DecoderWeights_13_out(BackPropagateDecoderWeights_U0_DecoderWeights_13_out),
    .DecoderWeights_13_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_13_out_ap_vld),
    .p_read14(p_read54),
    .DecoderWeights_14_out(BackPropagateDecoderWeights_U0_DecoderWeights_14_out),
    .DecoderWeights_14_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_14_out_ap_vld),
    .p_read15(p_read55),
    .DecoderWeights_15_out(BackPropagateDecoderWeights_U0_DecoderWeights_15_out),
    .DecoderWeights_15_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_15_out_ap_vld),
    .p_read16(p_read56),
    .DecoderWeights_16_out(BackPropagateDecoderWeights_U0_DecoderWeights_16_out),
    .DecoderWeights_16_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_16_out_ap_vld),
    .p_read17(p_read57),
    .DecoderWeights_17_out(BackPropagateDecoderWeights_U0_DecoderWeights_17_out),
    .DecoderWeights_17_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_17_out_ap_vld),
    .p_read18(p_read58),
    .DecoderWeights_18_out(BackPropagateDecoderWeights_U0_DecoderWeights_18_out),
    .DecoderWeights_18_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_18_out_ap_vld),
    .p_read19(p_read59),
    .DecoderWeights_19_out(BackPropagateDecoderWeights_U0_DecoderWeights_19_out),
    .DecoderWeights_19_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_19_out_ap_vld),
    .p_read20(p_read60),
    .DecoderWeights_20_out(BackPropagateDecoderWeights_U0_DecoderWeights_20_out),
    .DecoderWeights_20_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_20_out_ap_vld),
    .p_read21(p_read61),
    .DecoderWeights_21_out(BackPropagateDecoderWeights_U0_DecoderWeights_21_out),
    .DecoderWeights_21_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_21_out_ap_vld),
    .p_read22(p_read62),
    .DecoderWeights_22_out(BackPropagateDecoderWeights_U0_DecoderWeights_22_out),
    .DecoderWeights_22_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_22_out_ap_vld),
    .p_read23(p_read63),
    .DecoderWeights_23_out(BackPropagateDecoderWeights_U0_DecoderWeights_23_out),
    .DecoderWeights_23_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_23_out_ap_vld),
    .p_read24(p_read64),
    .DecoderWeights_24_out(BackPropagateDecoderWeights_U0_DecoderWeights_24_out),
    .DecoderWeights_24_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_24_out_ap_vld),
    .p_read25(p_read65),
    .DecoderWeights_25_out(BackPropagateDecoderWeights_U0_DecoderWeights_25_out),
    .DecoderWeights_25_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_25_out_ap_vld),
    .p_read26(p_read66),
    .DecoderWeights_26_out(BackPropagateDecoderWeights_U0_DecoderWeights_26_out),
    .DecoderWeights_26_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_26_out_ap_vld),
    .p_read27(p_read67),
    .DecoderWeights_27_out(BackPropagateDecoderWeights_U0_DecoderWeights_27_out),
    .DecoderWeights_27_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_27_out_ap_vld),
    .p_read28(p_read68),
    .DecoderWeights_28_out(BackPropagateDecoderWeights_U0_DecoderWeights_28_out),
    .DecoderWeights_28_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_28_out_ap_vld),
    .p_read29(p_read69),
    .DecoderWeights_29_out(BackPropagateDecoderWeights_U0_DecoderWeights_29_out),
    .DecoderWeights_29_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_29_out_ap_vld),
    .p_read30(p_read70),
    .DecoderWeights_30_out(BackPropagateDecoderWeights_U0_DecoderWeights_30_out),
    .DecoderWeights_30_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_30_out_ap_vld),
    .p_read31(p_read71),
    .DecoderWeights_31_out(BackPropagateDecoderWeights_U0_DecoderWeights_31_out),
    .DecoderWeights_31_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_31_out_ap_vld),
    .p_read32(p_read72),
    .DecoderWeights_32_out(BackPropagateDecoderWeights_U0_DecoderWeights_32_out),
    .DecoderWeights_32_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_32_out_ap_vld),
    .p_read33(p_read73),
    .DecoderWeights_33_out(BackPropagateDecoderWeights_U0_DecoderWeights_33_out),
    .DecoderWeights_33_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_33_out_ap_vld),
    .p_read34(p_read74),
    .DecoderWeights_34_out(BackPropagateDecoderWeights_U0_DecoderWeights_34_out),
    .DecoderWeights_34_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_34_out_ap_vld),
    .p_read35(p_read75),
    .DecoderWeights_35_out(BackPropagateDecoderWeights_U0_DecoderWeights_35_out),
    .DecoderWeights_35_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_35_out_ap_vld),
    .p_read36(p_read76),
    .DecoderWeights_36_out(BackPropagateDecoderWeights_U0_DecoderWeights_36_out),
    .DecoderWeights_36_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_36_out_ap_vld),
    .p_read37(p_read77),
    .DecoderWeights_37_out(BackPropagateDecoderWeights_U0_DecoderWeights_37_out),
    .DecoderWeights_37_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_37_out_ap_vld),
    .p_read38(p_read78),
    .DecoderWeights_38_out(BackPropagateDecoderWeights_U0_DecoderWeights_38_out),
    .DecoderWeights_38_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_38_out_ap_vld),
    .p_read39(p_read79),
    .DecoderWeights_39_out(BackPropagateDecoderWeights_U0_DecoderWeights_39_out),
    .DecoderWeights_39_out_ap_vld(BackPropagateDecoderWeights_U0_DecoderWeights_39_out_ap_vld),
    .PrevDecoderWeightChanges_address0(BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_address0),
    .PrevDecoderWeightChanges_ce0(BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_ce0),
    .PrevDecoderWeightChanges_we0(BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_we0),
    .PrevDecoderWeightChanges_d0(BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_BackPropagateDecoderWeightChanges_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_BackPropagateDecoderWeightChanges_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_BackPropagateDecoderWeightChanges_U0_ap_ready <= ap_sync_BackPropagateDecoderWeightChanges_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_BackPropagateDecoderWeights_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_BackPropagateDecoderWeights_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_BackPropagateDecoderWeights_U0_ap_ready <= ap_sync_BackPropagateDecoderWeights_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_BackPropagateEncoderWeightsChanges_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_BackPropagateEncoderWeightsChanges_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_BackPropagateEncoderWeightsChanges_U0_ap_ready <= ap_sync_BackPropagateEncoderWeightsChanges_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_BackPropagateEncoderWeights_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_BackPropagateEncoderWeights_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_BackPropagateEncoderWeights_U0_ap_ready <= ap_sync_BackPropagateEncoderWeights_U0_ap_ready;
        end
    end
end

assign BackPropagateDecoderWeightChanges_U0_ap_continue = ap_sync_continue;

assign BackPropagateDecoderWeightChanges_U0_ap_start = ((ap_sync_reg_BackPropagateDecoderWeightChanges_U0_ap_ready ^ 1'b1) & ap_start);

assign BackPropagateDecoderWeights_U0_ap_continue = ap_sync_continue;

assign BackPropagateDecoderWeights_U0_ap_start = ((ap_sync_reg_BackPropagateDecoderWeights_U0_ap_ready ^ 1'b1) & ap_start);

assign BackPropagateEncoderWeightsChanges_U0_ap_continue = ap_sync_continue;

assign BackPropagateEncoderWeightsChanges_U0_ap_start = ((ap_sync_reg_BackPropagateEncoderWeightsChanges_U0_ap_ready ^ 1'b1) & ap_start);

assign BackPropagateEncoderWeights_U0_ap_continue = ap_sync_continue;

assign BackPropagateEncoderWeights_U0_ap_start = ((ap_sync_reg_BackPropagateEncoderWeights_U0_ap_ready ^ 1'b1) & ap_start);

assign DecoderWeightChanges_address0 = BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_address0;

assign DecoderWeightChanges_address1 = 6'd0;

assign DecoderWeightChanges_ce0 = BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_ce0;

assign DecoderWeightChanges_ce1 = 1'b0;

assign DecoderWeightChanges_d0 = BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_d0;

assign DecoderWeightChanges_d1 = 1'd0;

assign DecoderWeightChanges_we0 = BackPropagateDecoderWeightChanges_U0_DecoderWeightChanges_we0;

assign DecoderWeightChanges_we1 = 1'b0;

assign DecoderWeights_0_out = BackPropagateDecoderWeights_U0_DecoderWeights_0_out;

assign DecoderWeights_0_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_0_out_ap_vld;

assign DecoderWeights_10_out = BackPropagateDecoderWeights_U0_DecoderWeights_10_out;

assign DecoderWeights_10_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_10_out_ap_vld;

assign DecoderWeights_11_out = BackPropagateDecoderWeights_U0_DecoderWeights_11_out;

assign DecoderWeights_11_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_11_out_ap_vld;

assign DecoderWeights_12_out = BackPropagateDecoderWeights_U0_DecoderWeights_12_out;

assign DecoderWeights_12_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_12_out_ap_vld;

assign DecoderWeights_13_out = BackPropagateDecoderWeights_U0_DecoderWeights_13_out;

assign DecoderWeights_13_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_13_out_ap_vld;

assign DecoderWeights_14_out = BackPropagateDecoderWeights_U0_DecoderWeights_14_out;

assign DecoderWeights_14_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_14_out_ap_vld;

assign DecoderWeights_15_out = BackPropagateDecoderWeights_U0_DecoderWeights_15_out;

assign DecoderWeights_15_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_15_out_ap_vld;

assign DecoderWeights_16_out = BackPropagateDecoderWeights_U0_DecoderWeights_16_out;

assign DecoderWeights_16_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_16_out_ap_vld;

assign DecoderWeights_17_out = BackPropagateDecoderWeights_U0_DecoderWeights_17_out;

assign DecoderWeights_17_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_17_out_ap_vld;

assign DecoderWeights_18_out = BackPropagateDecoderWeights_U0_DecoderWeights_18_out;

assign DecoderWeights_18_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_18_out_ap_vld;

assign DecoderWeights_19_out = BackPropagateDecoderWeights_U0_DecoderWeights_19_out;

assign DecoderWeights_19_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_19_out_ap_vld;

assign DecoderWeights_1_out = BackPropagateDecoderWeights_U0_DecoderWeights_1_out;

assign DecoderWeights_1_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_1_out_ap_vld;

assign DecoderWeights_20_out = BackPropagateDecoderWeights_U0_DecoderWeights_20_out;

assign DecoderWeights_20_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_20_out_ap_vld;

assign DecoderWeights_21_out = BackPropagateDecoderWeights_U0_DecoderWeights_21_out;

assign DecoderWeights_21_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_21_out_ap_vld;

assign DecoderWeights_22_out = BackPropagateDecoderWeights_U0_DecoderWeights_22_out;

assign DecoderWeights_22_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_22_out_ap_vld;

assign DecoderWeights_23_out = BackPropagateDecoderWeights_U0_DecoderWeights_23_out;

assign DecoderWeights_23_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_23_out_ap_vld;

assign DecoderWeights_24_out = BackPropagateDecoderWeights_U0_DecoderWeights_24_out;

assign DecoderWeights_24_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_24_out_ap_vld;

assign DecoderWeights_25_out = BackPropagateDecoderWeights_U0_DecoderWeights_25_out;

assign DecoderWeights_25_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_25_out_ap_vld;

assign DecoderWeights_26_out = BackPropagateDecoderWeights_U0_DecoderWeights_26_out;

assign DecoderWeights_26_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_26_out_ap_vld;

assign DecoderWeights_27_out = BackPropagateDecoderWeights_U0_DecoderWeights_27_out;

assign DecoderWeights_27_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_27_out_ap_vld;

assign DecoderWeights_28_out = BackPropagateDecoderWeights_U0_DecoderWeights_28_out;

assign DecoderWeights_28_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_28_out_ap_vld;

assign DecoderWeights_29_out = BackPropagateDecoderWeights_U0_DecoderWeights_29_out;

assign DecoderWeights_29_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_29_out_ap_vld;

assign DecoderWeights_2_out = BackPropagateDecoderWeights_U0_DecoderWeights_2_out;

assign DecoderWeights_2_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_2_out_ap_vld;

assign DecoderWeights_30_out = BackPropagateDecoderWeights_U0_DecoderWeights_30_out;

assign DecoderWeights_30_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_30_out_ap_vld;

assign DecoderWeights_31_out = BackPropagateDecoderWeights_U0_DecoderWeights_31_out;

assign DecoderWeights_31_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_31_out_ap_vld;

assign DecoderWeights_32_out = BackPropagateDecoderWeights_U0_DecoderWeights_32_out;

assign DecoderWeights_32_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_32_out_ap_vld;

assign DecoderWeights_33_out = BackPropagateDecoderWeights_U0_DecoderWeights_33_out;

assign DecoderWeights_33_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_33_out_ap_vld;

assign DecoderWeights_34_out = BackPropagateDecoderWeights_U0_DecoderWeights_34_out;

assign DecoderWeights_34_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_34_out_ap_vld;

assign DecoderWeights_35_out = BackPropagateDecoderWeights_U0_DecoderWeights_35_out;

assign DecoderWeights_35_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_35_out_ap_vld;

assign DecoderWeights_36_out = BackPropagateDecoderWeights_U0_DecoderWeights_36_out;

assign DecoderWeights_36_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_36_out_ap_vld;

assign DecoderWeights_37_out = BackPropagateDecoderWeights_U0_DecoderWeights_37_out;

assign DecoderWeights_37_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_37_out_ap_vld;

assign DecoderWeights_38_out = BackPropagateDecoderWeights_U0_DecoderWeights_38_out;

assign DecoderWeights_38_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_38_out_ap_vld;

assign DecoderWeights_39_out = BackPropagateDecoderWeights_U0_DecoderWeights_39_out;

assign DecoderWeights_39_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_39_out_ap_vld;

assign DecoderWeights_3_out = BackPropagateDecoderWeights_U0_DecoderWeights_3_out;

assign DecoderWeights_3_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_3_out_ap_vld;

assign DecoderWeights_4_out = BackPropagateDecoderWeights_U0_DecoderWeights_4_out;

assign DecoderWeights_4_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_4_out_ap_vld;

assign DecoderWeights_5_out = BackPropagateDecoderWeights_U0_DecoderWeights_5_out;

assign DecoderWeights_5_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_5_out_ap_vld;

assign DecoderWeights_6_out = BackPropagateDecoderWeights_U0_DecoderWeights_6_out;

assign DecoderWeights_6_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_6_out_ap_vld;

assign DecoderWeights_7_out = BackPropagateDecoderWeights_U0_DecoderWeights_7_out;

assign DecoderWeights_7_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_7_out_ap_vld;

assign DecoderWeights_8_out = BackPropagateDecoderWeights_U0_DecoderWeights_8_out;

assign DecoderWeights_8_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_8_out_ap_vld;

assign DecoderWeights_9_out = BackPropagateDecoderWeights_U0_DecoderWeights_9_out;

assign DecoderWeights_9_out_ap_vld = BackPropagateDecoderWeights_U0_DecoderWeights_9_out_ap_vld;

assign Deltas_address0 = BackPropagateDecoderWeightChanges_U0_Deltas_address0;

assign Deltas_address1 = 2'd0;

assign Deltas_ce0 = BackPropagateDecoderWeightChanges_U0_Deltas_ce0;

assign Deltas_ce1 = 1'b0;

assign Deltas_d0 = BackPropagateDecoderWeightChanges_U0_Deltas_d0;

assign Deltas_d1 = 1'd0;

assign Deltas_we0 = BackPropagateDecoderWeightChanges_U0_Deltas_we0;

assign Deltas_we1 = 1'b0;

assign EncoderWeightChanges_address0 = BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_address0;

assign EncoderWeightChanges_address1 = 6'd0;

assign EncoderWeightChanges_ce0 = BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_ce0;

assign EncoderWeightChanges_ce1 = 1'b0;

assign EncoderWeightChanges_d0 = BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_d0;

assign EncoderWeightChanges_d1 = 1'd0;

assign EncoderWeightChanges_we0 = BackPropagateEncoderWeightsChanges_U0_EncoderWeightChanges_we0;

assign EncoderWeightChanges_we1 = 1'b0;

assign EncoderWeights_0_out = BackPropagateEncoderWeights_U0_EncoderWeights_0_out;

assign EncoderWeights_0_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_0_out_ap_vld;

assign EncoderWeights_10_out = BackPropagateEncoderWeights_U0_EncoderWeights_10_out;

assign EncoderWeights_10_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_10_out_ap_vld;

assign EncoderWeights_11_out = BackPropagateEncoderWeights_U0_EncoderWeights_11_out;

assign EncoderWeights_11_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_11_out_ap_vld;

assign EncoderWeights_12_out = BackPropagateEncoderWeights_U0_EncoderWeights_12_out;

assign EncoderWeights_12_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_12_out_ap_vld;

assign EncoderWeights_13_out = BackPropagateEncoderWeights_U0_EncoderWeights_13_out;

assign EncoderWeights_13_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_13_out_ap_vld;

assign EncoderWeights_14_out = BackPropagateEncoderWeights_U0_EncoderWeights_14_out;

assign EncoderWeights_14_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_14_out_ap_vld;

assign EncoderWeights_15_out = BackPropagateEncoderWeights_U0_EncoderWeights_15_out;

assign EncoderWeights_15_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_15_out_ap_vld;

assign EncoderWeights_16_out = BackPropagateEncoderWeights_U0_EncoderWeights_16_out;

assign EncoderWeights_16_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_16_out_ap_vld;

assign EncoderWeights_17_out = BackPropagateEncoderWeights_U0_EncoderWeights_17_out;

assign EncoderWeights_17_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_17_out_ap_vld;

assign EncoderWeights_18_out = BackPropagateEncoderWeights_U0_EncoderWeights_18_out;

assign EncoderWeights_18_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_18_out_ap_vld;

assign EncoderWeights_19_out = BackPropagateEncoderWeights_U0_EncoderWeights_19_out;

assign EncoderWeights_19_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_19_out_ap_vld;

assign EncoderWeights_1_out = BackPropagateEncoderWeights_U0_EncoderWeights_1_out;

assign EncoderWeights_1_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_1_out_ap_vld;

assign EncoderWeights_20_out = BackPropagateEncoderWeights_U0_EncoderWeights_20_out;

assign EncoderWeights_20_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_20_out_ap_vld;

assign EncoderWeights_21_out = BackPropagateEncoderWeights_U0_EncoderWeights_21_out;

assign EncoderWeights_21_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_21_out_ap_vld;

assign EncoderWeights_22_out = BackPropagateEncoderWeights_U0_EncoderWeights_22_out;

assign EncoderWeights_22_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_22_out_ap_vld;

assign EncoderWeights_23_out = BackPropagateEncoderWeights_U0_EncoderWeights_23_out;

assign EncoderWeights_23_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_23_out_ap_vld;

assign EncoderWeights_24_out = BackPropagateEncoderWeights_U0_EncoderWeights_24_out;

assign EncoderWeights_24_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_24_out_ap_vld;

assign EncoderWeights_25_out = BackPropagateEncoderWeights_U0_EncoderWeights_25_out;

assign EncoderWeights_25_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_25_out_ap_vld;

assign EncoderWeights_26_out = BackPropagateEncoderWeights_U0_EncoderWeights_26_out;

assign EncoderWeights_26_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_26_out_ap_vld;

assign EncoderWeights_27_out = BackPropagateEncoderWeights_U0_EncoderWeights_27_out;

assign EncoderWeights_27_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_27_out_ap_vld;

assign EncoderWeights_28_out = BackPropagateEncoderWeights_U0_EncoderWeights_28_out;

assign EncoderWeights_28_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_28_out_ap_vld;

assign EncoderWeights_29_out = BackPropagateEncoderWeights_U0_EncoderWeights_29_out;

assign EncoderWeights_29_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_29_out_ap_vld;

assign EncoderWeights_2_out = BackPropagateEncoderWeights_U0_EncoderWeights_2_out;

assign EncoderWeights_2_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_2_out_ap_vld;

assign EncoderWeights_30_out = BackPropagateEncoderWeights_U0_EncoderWeights_30_out;

assign EncoderWeights_30_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_30_out_ap_vld;

assign EncoderWeights_31_out = BackPropagateEncoderWeights_U0_EncoderWeights_31_out;

assign EncoderWeights_31_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_31_out_ap_vld;

assign EncoderWeights_32_out = BackPropagateEncoderWeights_U0_EncoderWeights_32_out;

assign EncoderWeights_32_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_32_out_ap_vld;

assign EncoderWeights_33_out = BackPropagateEncoderWeights_U0_EncoderWeights_33_out;

assign EncoderWeights_33_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_33_out_ap_vld;

assign EncoderWeights_34_out = BackPropagateEncoderWeights_U0_EncoderWeights_34_out;

assign EncoderWeights_34_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_34_out_ap_vld;

assign EncoderWeights_35_out = BackPropagateEncoderWeights_U0_EncoderWeights_35_out;

assign EncoderWeights_35_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_35_out_ap_vld;

assign EncoderWeights_36_out = BackPropagateEncoderWeights_U0_EncoderWeights_36_out;

assign EncoderWeights_36_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_36_out_ap_vld;

assign EncoderWeights_37_out = BackPropagateEncoderWeights_U0_EncoderWeights_37_out;

assign EncoderWeights_37_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_37_out_ap_vld;

assign EncoderWeights_38_out = BackPropagateEncoderWeights_U0_EncoderWeights_38_out;

assign EncoderWeights_38_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_38_out_ap_vld;

assign EncoderWeights_39_out = BackPropagateEncoderWeights_U0_EncoderWeights_39_out;

assign EncoderWeights_39_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_39_out_ap_vld;

assign EncoderWeights_3_out = BackPropagateEncoderWeights_U0_EncoderWeights_3_out;

assign EncoderWeights_3_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_3_out_ap_vld;

assign EncoderWeights_4_out = BackPropagateEncoderWeights_U0_EncoderWeights_4_out;

assign EncoderWeights_4_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_4_out_ap_vld;

assign EncoderWeights_5_out = BackPropagateEncoderWeights_U0_EncoderWeights_5_out;

assign EncoderWeights_5_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_5_out_ap_vld;

assign EncoderWeights_6_out = BackPropagateEncoderWeights_U0_EncoderWeights_6_out;

assign EncoderWeights_6_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_6_out_ap_vld;

assign EncoderWeights_7_out = BackPropagateEncoderWeights_U0_EncoderWeights_7_out;

assign EncoderWeights_7_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_7_out_ap_vld;

assign EncoderWeights_8_out = BackPropagateEncoderWeights_U0_EncoderWeights_8_out;

assign EncoderWeights_8_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_8_out_ap_vld;

assign EncoderWeights_9_out = BackPropagateEncoderWeights_U0_EncoderWeights_9_out;

assign EncoderWeights_9_out_ap_vld = BackPropagateEncoderWeights_U0_EncoderWeights_9_out_ap_vld;

assign PrevDecoderWeightChanges_address0 = BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_address0;

assign PrevDecoderWeightChanges_address1 = 6'd0;

assign PrevDecoderWeightChanges_ce0 = BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_ce0;

assign PrevDecoderWeightChanges_ce1 = 1'b0;

assign PrevDecoderWeightChanges_d0 = BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_d0;

assign PrevDecoderWeightChanges_d1 = 1'd0;

assign PrevDecoderWeightChanges_we0 = BackPropagateDecoderWeights_U0_PrevDecoderWeightChanges_we0;

assign PrevDecoderWeightChanges_we1 = 1'b0;

assign PrevEncoderWeightChanges_address0 = BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_address0;

assign PrevEncoderWeightChanges_address1 = 6'd0;

assign PrevEncoderWeightChanges_ce0 = BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_ce0;

assign PrevEncoderWeightChanges_ce1 = 1'b0;

assign PrevEncoderWeightChanges_d0 = BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_d0;

assign PrevEncoderWeightChanges_d1 = 1'd0;

assign PrevEncoderWeightChanges_we0 = BackPropagateEncoderWeights_U0_PrevEncoderWeightChanges_we0;

assign PrevEncoderWeightChanges_we1 = 1'b0;

assign TotalErrorDeltas_address0 = BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_address0;

assign TotalErrorDeltas_address1 = 6'd0;

assign TotalErrorDeltas_ce0 = BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_ce0;

assign TotalErrorDeltas_ce1 = 1'b0;

assign TotalErrorDeltas_d0 = BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_d0;

assign TotalErrorDeltas_d1 = 1'd0;

assign TotalErrorDeltas_we0 = BackPropagateEncoderWeightsChanges_U0_TotalErrorDeltas_we0;

assign TotalErrorDeltas_we1 = 1'b0;

assign ap_done = ap_sync_done;

assign ap_idle = (BackPropagateEncoderWeights_U0_ap_idle & BackPropagateEncoderWeightsChanges_U0_ap_idle & BackPropagateDecoderWeights_U0_ap_idle & BackPropagateDecoderWeightChanges_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_BackPropagateDecoderWeightChanges_U0_ap_ready = (ap_sync_reg_BackPropagateDecoderWeightChanges_U0_ap_ready | BackPropagateDecoderWeightChanges_U0_ap_ready);

assign ap_sync_BackPropagateDecoderWeights_U0_ap_ready = (ap_sync_reg_BackPropagateDecoderWeights_U0_ap_ready | BackPropagateDecoderWeights_U0_ap_ready);

assign ap_sync_BackPropagateEncoderWeightsChanges_U0_ap_ready = (ap_sync_reg_BackPropagateEncoderWeightsChanges_U0_ap_ready | BackPropagateEncoderWeightsChanges_U0_ap_ready);

assign ap_sync_BackPropagateEncoderWeights_U0_ap_ready = (ap_sync_reg_BackPropagateEncoderWeights_U0_ap_ready | BackPropagateEncoderWeights_U0_ap_ready);

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (BackPropagateEncoderWeights_U0_ap_done & BackPropagateEncoderWeightsChanges_U0_ap_done & BackPropagateDecoderWeights_U0_ap_done & BackPropagateDecoderWeightChanges_U0_ap_done);

assign ap_sync_ready = (ap_sync_BackPropagateEncoderWeights_U0_ap_ready & ap_sync_BackPropagateEncoderWeightsChanges_U0_ap_ready & ap_sync_BackPropagateDecoderWeights_U0_ap_ready & ap_sync_BackPropagateDecoderWeightChanges_U0_ap_ready);

endmodule //Autoencoder_BackPropagate
